// swift-tools-version:6.0
import Foundation
import PackageDescription

let binaryBaseURL = "https://github.com/dooop/swift-scummvm/releases/download/0.2.0"

// Prebuilt ScummVM engine + platform glue. Published by .github/workflows/release-engine.yml;
// bump the tag and all three checksums together when a new engine build ships.
let engineBinaryBaseURL = "https://github.com/dooop/swift-scummvm/releases/download/0.5.2"
let engineChecksumiOS = "f3b914b6283bc038f9107afe9b5a2ce27f547b3aaf501783d499bc3b6c2426f2"
let engineChecksumtvOS = "31ba404b22c6b4e1a50cb4e871454fea57d8fcd7142ba4bb1bad290804cd4e68"
let engineChecksummacOS = "a0ce4bc9aa1e74dc8003bead80b45aeb82b475d79f624b90b836bb725fcc68d9"
// Internal release validation can point binary mode at freshly assembled local
// XCFrameworks before they are published. The path is relative to the package root.
let localEngineArtifactsPath = ProcessInfo.processInfo.environment["SCUMMVM_ENGINE_ARTIFACTS_DIR"]

// Consumers link the prebuilt engine: ~7,700 upstream translation units and the
// 534 MB submodule checkout drop out of their build entirely.
//
// Set SCUMMVM_BUILD_FROM_SOURCE=1 to compile the engine from scummvm
// instead - required when touching engine code, overrides or the platform glue, and
// used by the release pipeline itself. SwiftPM caches the parsed manifest by content,
// not by environment, so run `swift package reset` when flipping the switch.
let buildEngineFromSource = ProcessInfo.processInfo.environment["SCUMMVM_BUILD_FROM_SOURCE"] != nil

// Source-mode-only resource rules for the ScummVMtvOS re-export target (see its
// definition in engineTargets below). Binary mode ships a real ScummVMtvOS
// XCFramework instead, with these assets already baked into its Resources.
let tvOSResources: [Resource] = [
  .process("../../scummvm/dists/tvos/Images.xcassets"),
  .copy("../../scummvm/dists/tvos/PrivacyInfo.xcprivacy"),
]

// Engine + platform glue: compiled from the submodule in source mode, downloaded as
// prebuilt dynamic-framework XCFrameworks otherwise. The two modes are mutually
// exclusive, so the binary targets reuse the source target names and every dependent
// target's dependency list stays identical either way.
//
// The prebuilt frameworks are dynamic and link the third-party static libraries and
// system frameworks into themselves, and they carry the runtime payload in their own
// Resources directory. In binary mode none of that appears in the consumer's graph -
// they resolve two artifacts instead of twenty-six, with no submodule in sight.
let engineTargets: [Target] =
  buildEngineFromSource
  ? [
      .target(
        name: "ScummVMEngine",
        dependencies: [
          "a52", "bz2", "curl", "faad", "ffi", "FLAC", "fluidsynth",
          "freetype", "fribidi", "gif", "glib-2.0", "intl", "jpeg",
          "mad", "mikmod", "mpeg2", "ogg", "png", "SDL2_net",
          "theoradec", "vorbis", "vorbisfile", "vpx",
          .target(name: "SDL2", condition: .when(platforms: [.macOS])),
        ],
        path: ".",
        exclude: [
          // Upstream non-runtime directories.
          "scummvm/devtools",
          "scummvm/dists",
          "scummvm/test",
          "scummvm/doc",
          "scummvm/po",
          "scummvm/icons",
          "scummvm/LICENSES",
          // Keep runtime payload on explicit resource copy rules (avoid auto resource duplication)
          "scummvm/gui/themes",
          // Prevent duplicate asset names (iOS + tvOS variants share filenames).
          "scummvm/dists/tvos",
          // Upstream files excluded from this target
          "scummvm/engines/ags/tests",
          "scummvm/engines/glk/adrift/sxstubs.cpp",
          "scummvm/engines/glk/adrift/sxscript.cpp",
          "scummvm/backends/platform/android",
          "scummvm/backends/platform/ios7",
          // macOS SDL backend is built in ScummVMmacOS target
          "scummvm/backends/platform/sdl",
          "scummvm/backends/platform/psp",
          "scummvm/backends/platform/3ds",
          "scummvm/backends/platform/maemo",
          "scummvm/backends/platform/n64",
          "scummvm/backends/platform/openpandora",
          "scummvm/backends/platform/samsungtv",
          "scummvm/backends/platform/wii",
          "scummvm/backends/platform/null",
          "scummvm/backends/platform/libretro",
          "scummvm/backends/platform/libretro/src/libretro-threads.cpp",
          "scummvm/backends/events/maemosdl",
          "scummvm/backends/events/openpandora",
          "scummvm/backends/events/ps3sdl",
          "scummvm/backends/events/psp2sdl",
          "scummvm/backends/events/riscossdl",
          "scummvm/backends/events/samsungtvsdl",
          "scummvm/backends/events/switchsdl",
          "scummvm/backends/graphics/maemosdl",
          "scummvm/backends/graphics/openpandora",
          "scummvm/backends/graphics/riscossdl",
          "scummvm/backends/dialogs/amigaos",
          "scummvm/backends/dialogs/gtk",
          "scummvm/backends/dialogs/morphos",
          "scummvm/backends/dialogs/win32",
          "scummvm/backends/audiocd/linux",
          "scummvm/backends/audiocd/win32",
          "scummvm/backends/audiocd/atari",
          "scummvm/backends/networking/basic/android",
          "scummvm/backends/networking/http/android",
          "scummvm/backends/networking/http/emscripten",
          "scummvm/backends/networking/enet/source/win32.cpp",
          "scummvm/video/mkv_decoder.cpp",
          // Override to support builds without ENABLE_EVENTRECORDER (e.g. iOS/tvOS)
          "scummvm/common/recorderfile.cpp",
          "scummvm/gui/updates-dialog.cpp",
          // Override to support builds without ENABLE_EVENTRECORDER (e.g. iOS/tvOS)
          "scummvm/gui/recorderdialog.cpp",
          // Override to support builds without ENABLE_EVENTRECORDER (e.g. iOS/tvOS)
          "scummvm/gui/onscreendialog.cpp",
          // Override: fixes a U32String/String comparison mismatch (pre-existing
          // upstream bug, unrelated to this package's configuration)
          "scummvm/gui/downloaddlcsdialog.cpp",
          // Override: isImGuiRecorderEnabled() turned into a free function
          // (see override file for why a header-only fix doesn't work here)
          "scummvm/gui/EventRecorder.cpp",
          "scummvm/common/updates.cpp",
          "scummvm/backends/taskbar",
          "scummvm/backends/fs/android",
          "scummvm/backends/fs/kolibrios",
          "scummvm/backends/fs/emscripten",
          "scummvm/backends/fs/atari",
          "scummvm/backends/fs/amigaos",
          "scummvm/backends/fs/devoptab",
          "scummvm/backends/fs/morphos",
          "scummvm/backends/fs/n64",
          "scummvm/backends/fs/ps3",
          "scummvm/backends/fs/psp",
          "scummvm/backends/fs/riscos",
          "scummvm/backends/fs/wii",
          "scummvm/backends/fs/windows",
          "scummvm/backends/graphics/sdl",
          "scummvm/backends/graphics/surfacesdl",
          "scummvm/backends/graphics/openglsdl",
          "scummvm/backends/graphics/ios",
          "scummvm/backends/graphics/android",
          "scummvm/backends/graphics/opendingux",
          "scummvm/backends/graphics/miyoo",
          "scummvm/backends/saves/kolibrios",
          "scummvm/backends/saves/windows/windows-saves.cpp",
          // Override to support builds without ENABLE_EVENTRECORDER (e.g. iOS/tvOS)
          "scummvm/backends/saves/recorder/recorder-saves.cpp",
          // x86 SSE/AVX intrinsics – not compilable on ARM
          "scummvm/graphics/blit/blit-sse2.cpp",
          "scummvm/graphics/blit/blit-avx2.cpp",
          "scummvm/graphics/blit/blit-atari.cpp",
          // Generated larryScale code depends on missing generator headers
          "scummvm/graphics/larryScale_generated.cpp",
          "scummvm/engines/ags/lib/allegro/surface_sse2.cpp",
          "scummvm/engines/ags/lib/allegro/surface_avx2.cpp",
          "scummvm/engines/ags/lib/allegro/fmaths.cpp",
          "scummvm/engines/titanic/game/transport/exit_pellerator.cpp",
          // ARM32 assembly – incompatible with arm64
          "scummvm/graphics/scaler/scale2xARM.s",
          "scummvm/graphics/scaler/Normal2xARM.s",
          "scummvm/graphics/scaler/downscalerARM.s",
          "scummvm/engines/grim/movie/codecs/blocky8ARM.s",
          "scummvm/engines/scumm/gfxARM.s",
          "scummvm/engines/scumm/smush/codec47ARM.s",
          // M68K assembly (Amiga/Atari) – incompatible with arm64/x86_64
          "scummvm/engines/scumm/gfxM68K.S",
          "scummvm/engines/scumm/m68k",
          // Rebel Assault II PSX support: gated upstream behind ENABLE_REBEL2_PSX,
          // which this package does not define; unlike scumm.cpp's own references
          // (properly #ifdef-guarded), these sources reference the gated types
          // unconditionally and fail to compile without the flag.
          "scummvm/engines/scumm/insane/rebel2/psx",
          // Platform-specific assembly (Atari, DS, Dreamcast)
          "scummvm/backends/graphics/atari",
          "scummvm/backends/platform/atari",
          "scummvm/backends/platform/dc",
          "scummvm/backends/platform/ds",
          "scummvm/backends/mixer/atari",
          "scummvm/backends/mixer/android",
          "scummvm/backends/mixer/emscriptensdl",
          "scummvm/backends/midi/camd.cpp",
          "scummvm/backends/midi/dmedia.cpp",
          "scummvm/backends/midi/riscos.cpp",
          "scummvm/backends/midi/sndio.cpp",
          "scummvm/backends/midi/stmidi.cpp",
          "scummvm/backends/midi/webmidi.cpp",
          "scummvm/backends/midi/windows.cpp",
          "scummvm/backends/mixer/maxmod",
          "scummvm/backends/mutex/3ds",
          "scummvm/backends/mutex/wii",
          "scummvm/backends/plugins/3ds",
          "scummvm/backends/plugins/ds",
          "scummvm/backends/plugins/kolibrios",
          "scummvm/backends/plugins/psp",
          "scummvm/backends/plugins/psp2",
          "scummvm/backends/plugins/riscos",
          "scummvm/backends/plugins/wii",
          "scummvm/backends/plugins/win32",
          "scummvm/backends/plugins/atari",
          "scummvm/backends/plugins/elf",
          "scummvm/backends/plugins/firebee",
          "scummvm/backends/plugins/mintelf",
          "scummvm/backends/printing/win32",
          "scummvm/backends/text-to-speech/emscripten",
          "scummvm/backends/text-to-speech/linux",
          "scummvm/backends/text-to-speech/windows",
          "scummvm/backends/updates/win32",
          "scummvm/backends/timer/psp",
          "scummvm/backends/timer/emscripten",
          // RetroWave hardware OPL3 – requires external library
          "scummvm/audio/rwopl3.cpp",
          // OPL2LPT/OPL3LPT – requires libieee1284
          "scummvm/audio/opl2lpt.cpp",
          // ALSA OPL – requires ALSA headers
          "scummvm/audio/alsa_opl.cpp",
          // nFM hardware OPL boards – requires the external nfm library headers
          // (nfmcore.h/nfmutil.h); gated upstream behind USE_NFM in fmopl.cpp,
          // but this standalone TU includes them unconditionally.
          "scummvm/audio/nfmopl.cpp",
          // Atari YM2149 chip backend – includes Atari MiNT/TOS system headers
          // unconditionally; gated upstream behind #ifdef ATARI in ym2149.cpp.
          "scummvm/audio/atari_ym2149.cpp",
          // libsoxr adapter – requires soxr headers
          "scummvm/audio/softsynth/mt32/srchelper/SoxrAdapter.cpp",
          "scummvm/audio/softsynth/mt32/srchelper/SoxrAdapter.h",
          // libsamplerate adapter – requires samplerate headers
          "scummvm/audio/softsynth/mt32/srchelper/SamplerateAdapter.cpp",
          "scummvm/audio/softsynth/mt32/srchelper/SamplerateAdapter.h",
          // Engine not enabled / missing headers
          "scummvm/engines/icb",
          // Engine modules disabled by current ENABLE_* selection in Package.swift.
          "scummvm/engines/agds",
          "scummvm/engines/alcachofa",
          "scummvm/engines/alg",
          "scummvm/engines/avalanche",
          "scummvm/engines/awe",
          "scummvm/engines/bolt",
          "scummvm/engines/chamber",
          "scummvm/engines/colony",
          "scummvm/engines/cryo",
          "scummvm/engines/dm",
          "scummvm/engines/eem",
          "scummvm/engines/fool",
          "scummvm/engines/gamos",
          "scummvm/engines/got",
          "scummvm/engines/harvester",
          "scummvm/engines/hpl1",
          "scummvm/engines/immortal",
          "scummvm/engines/lastexpress",
          "scummvm/engines/lilliput",
          "scummvm/engines/macs2",
          "scummvm/engines/macventure",
          "scummvm/engines/mediastation",
          "scummvm/engines/mutationofjb",
          "scummvm/engines/pelrock",
          "scummvm/engines/phoenixvr",
          "scummvm/engines/playground3d",
          "scummvm/engines/sludge",
          "scummvm/engines/startrek",
          "scummvm/engines/testbed",
          "scummvm/engines/tot",
          "scummvm/engines/wage",
          "scummvm/engines/watchmaker",
          "scummvm/engines/waynesworld",
          // Static data file – compiled via include from another TU
          "scummvm/engines/supernova/screenstatic.cpp",
          // Macro-templated sprite-draw body – #include-d 12x by sprite.cpp with
          // different macros predefined each time, not a standalone TU
          "scummvm/engines/mads/core/sprite_0.cpp",
          // Orphaned duplicate of dont_frag_the_palette()/sprite_free()/etc.,
          // which sprite.cpp already defines itself; not #include-d or
          // referenced anywhere, and collides as a standalone TU
          "scummvm/engines/mads/core/sprite_k.cpp",
          // Buggy plugin stub – missing includes and wrong function names
          "scummvm/engines/ags/plugins/core/screen.cpp",
          // SDL3 backend – we use SDL2
          "scummvm/backends/events/sdl/sdl3-events.cpp",
          // SDL1 backend – we use SDL2
          "scummvm/backends/events/sdl/sdl1-events.cpp",
          "scummvm/backends/events/ds",
          "scummvm/backends/events/atari",
          "scummvm/backends/events/default/default-events.cpp",
          // SDL3 ImGui backend – we use SDL2
          "scummvm/backends/imgui/backends/imgui_impl_sdlrenderer3.cpp",
          "scummvm/backends/imgui/backends/imgui_impl_sdl3.cpp",
          // SDL2 ImGui backends are macOS-only in this package setup (iOS/tvOS builds use WITHOUT_SDL)
          "scummvm/backends/imgui/backends/imgui_impl_sdl2.cpp",
          "scummvm/backends/imgui/backends/imgui_impl_sdlrenderer2.cpp",
          "scummvm/base/main.cpp",
          "scummvm/engines/ags/engine/main/main.cpp",
          "scummvm/engines/bladerunner/script/ai/_template.cpp",
          "scummvm/engines/bagel",
          "scummvm/engines/bagel/hodjnpodj/archeroids/main.cpp",
          "scummvm/engines/bagel/hodjnpodj/barbershop/main.cpp",
          "scummvm/engines/bagel/hodjnpodj/crypt/main.cpp",
          "scummvm/engines/bagel/hodjnpodj/metagame",
          "scummvm/engines/bagel/hodjnpodj/novacancy/main.cpp",
          "scummvm/engines/bagel/hodjnpodj/pdq/main.cpp",
          "scummvm/engines/bagel/hodjnpodj/pdq/convert.cpp",
          "Sources/ScummVMEngineOverrides/backends/platform/ios7/ios7_video.mm",
          "Sources/ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_video.mm",
          "Sources/ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_main.cpp",
          "Sources/ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_events.cpp",
          "Sources/ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_sound.cpp",
          "Sources/ScummVMEngineOverrides/engines/got/game/got_game_main_override.cpp",
          "Sources/ScummVMEngineOverrides/engines/watchmaker/watchmaker_main_override.cpp",
          "scummvm/engines/chewy/main.cpp",
          "scummvm/engines/mads/dragonsphere/main.cpp",
          "scummvm/engines/mads/nebular/main.cpp",
          "scummvm/engines/mads/phantom/main.cpp",
          "scummvm/engines/mads/forest/main.cpp",
          "scummvm/engines/glk/alan2/main.cpp",
          "scummvm/engines/glk/alan3/main.cpp",
          "scummvm/engines/got/game/main.cpp",
          "scummvm/engines/petka/interfaces/main.cpp",
          "scummvm/engines/scumm/he/net/net_lobby.cpp",
          "scummvm/engines/ultima/ultima1/widgets/merchant_armor.cpp",
          "scummvm/engines/ultima/ultima1/actions/cast.cpp",
          "scummvm/engines/saga2/main.cpp",
          "scummvm/engines/watchmaker/main.cpp",
          "scummvm/engines/dgds/sound/drivers/fmtowns.cpp",
          "scummvm/engines/director/debugger",
          "scummvm/engines/qdengine/debugger/debugtools.cpp",
        ],
        sources: [
          "scummvm",
          "Sources/ScummVMEngineOverrides",
        ],
        resources: [
          // Core runtime payload expected by ScummVM. In binary mode the release
          // pipeline copies the same files into the framework's own Resources
          // directory - see Scripts/build-engine-slice.sh, keep the two in sync.
          .copy("scummvm/dists/engine-data"),
          .copy("scummvm/dists/networking/wwwroot.zip"),
          .copy("scummvm/dists/soundfonts/Roland_SC-55.sf2"),
          .copy("scummvm/dists/soundfonts/COPYRIGHT.Roland_SC-55"),
          .copy("scummvm/dists/pred.dic"),

          // Theme payload (copy only runtime artifacts, not full source theme tree)
          .copy("scummvm/gui/themes/gui-icons.dat"),
          .copy("scummvm/gui/themes/residualvm.zip"),
          .copy("scummvm/gui/themes/scummclassic.zip"),
          .copy("scummvm/gui/themes/scummmodern.zip"),
          .copy("scummvm/gui/themes/scummremastered.zip"),
          .copy("scummvm/gui/themes/shaders.dat"),
          .copy("scummvm/gui/themes/translations.dat"),
        ],
        publicHeadersPath: "scummvm",
        cSettings: [
          // ScummVM sources are configured for RELEASE_BUILD in this package.
          // SwiftPM debug builds inject DEBUG=1 by default, which enables
          // debug-only code paths that rely on symbols not present here.
          .unsafeFlags(["-UDEBUG"])
        ],
        cxxSettings: [
          .headerSearchPath("."),
          .headerSearchPath("Sources/ScummVMEngineOverrides"),
          .headerSearchPath("scummvm"),
          .headerSearchPath("scummvm/engines"),
          .unsafeFlags(["-UDEBUG"]),
          .unsafeFlags(["-fno-objc-arc"], .when(platforms: [.macOS])),
          .unsafeFlags(["-UYES", "-UNO"], .when(platforms: [.macOS])),
          .unsafeFlags(["-include", "ScummVMNoObjCMacros.h"], .when(platforms: [.macOS])),
          .unsafeFlags(["-include", "ScummVMObjCYesNoConsts.h"], .when(platforms: [.macOS])),
          .unsafeFlags(["-include", "ScummVMAGSAlconfigBridge.h"]),
          .define("ENABLE_EVENTRECORDER", .when(platforms: [.macOS])),
          .define("ENABLE_WME3D"),
          .define("USE_ZLIB"),
          .define("USE_MAD"),
          .define("USE_FRIBIDI"),
          .define("USE_OGG"),
          .define("USE_VORBIS"),
          .define("USE_FLAC"),
          .define("USE_PNG"),
          .define("USE_GIF"),
          .define("USE_FAAD"),
          .define("USE_MIKMOD"),
          .define("USE_MPEG2"),
          .define("USE_THEORADEC"),
          .define("USE_FREETYPE2"),
          .define("USE_JPEG"),
          .define("USE_FLUIDSYNTH"),
          .define("USE_LIBCURL"),
          .define("USE_SDL_NET"),
          .define("USE_BINK"),
          .define("USE_SCALERS"),
          .define("USE_HQ_SCALERS"),
          .define("USE_EDGE_SCALERS"),
          .define("USE_ASPECT"),
          .define("USE_RGB_COLOR"),
          .define("USE_HIGHRES"),
          .define("USE_MT32EMU"),
          .define("USE_OPENGL"),
          .define("USE_OPENGL_GAME"),
          .define("USE_OPENGL_SHADERS"),
          .define("USE_CLOUD"),
          .define("USE_ENET"),
          .define("USE_TRANSLATION"),
          .define("USE_SYSDIALOGS"),
          .define("USE_DETECTLANG"),
          .define("BUILTIN_RESOURCES", .when(platforms: [.macOS])),
          .define("USE_DETECTION_FEATURES_STATIC"),
          .define("USE_FMTOWNS_PC98_AUDIO"),
          .define("USE_HNM"),
          .define("USE_INDEO3"),
          .define("USE_INDEO45"),
          .define("USE_LUA"),
          .define("USE_MIDI"),
          .define("USE_SID_AUDIO"),
          .define("USE_TINYGL"),
          .define("USE_UNIVERSALTRACKER"),
          .define("USE_VGMTRANS_AUDIO"),
          .define("ENABLE_SCUMM"),
          .define("ENABLE_SCUMM_7_8"),
          .define("ENABLE_HE"),
          .define("ENABLE_ACCESS"),
          .define("ENABLE_ADL"),
          .define("ENABLE_AGI"),
          .define("ENABLE_AGOS"),
          .define("ENABLE_AGOS2"),
          .define("ENABLE_AGS"),
          .define("ENABLE_ASYLUM"),
          .define("ENABLE_BBVS"),
          .define("ENABLE_BLADERUNNER"),
          .define("ENABLE_BURIED"),
          .define("ENABLE_CGE"),
          .define("ENABLE_CGE2"),
          .define("ENABLE_CHEWY"),
          .define("ENABLE_CINE"),
          .define("ENABLE_COMPOSER"),
          .define("ENABLE_CRAB"),
          .define("ENABLE_CRUISE"),
          .define("ENABLE_CRYOMNI3D"),
          .define("ENABLE_VERSAILLES"),
          .define("ENABLE_DARKSEED"),
          .define("ENABLE_DGDS"),
          .define("ENABLE_DIRECTOR"),
          .define("ENABLE_DRACI"),
          .define("ENABLE_DRAGONS"),
          .define("ENABLE_DRASCULA"),
          .define("ENABLE_DREAMWEB"),
          .define("ENABLE_EFH"),
          .define("ENABLE_FREESCAPE"),
          .define("ENABLE_GLK"),
          .define("ENABLE_GNAP"),
          .define("ENABLE_GOB"),
          .define("ENABLE_GRIFFON"),
          .define("ENABLE_GRIM"),
          .define("ENABLE_GROOVIE"),
          .define("ENABLE_GROOVIE2"),
          .define("ENABLE_HADESCH"),
          .define("ENABLE_HDB"),
          .define("ENABLE_HOPKINS"),
          .define("ENABLE_HUGO"),
          .define("ENABLE_HYPNO"),
          .define("ENABLE_ILLUSIONS"),
          .define("ENABLE_KINGDOM"),
          .define("ENABLE_KYRA"),
          .define("ENABLE_LOL"),
          .define("ENABLE_EOB"),
          .define("ENABLE_LAB"),
          .define("ENABLE_LURE"),
          .define("ENABLE_M4"),
          .define("ENABLE_MADE"),
          .define("ENABLE_MADS"),
          .define("ENABLE_MM"),
          .define("ENABLE_MM1"),
          .define("ENABLE_XEEN"),
          .define("ENABLE_MOHAWK"),
          .define("ENABLE_CSTIME"),
          .define("ENABLE_RIVEN"),
          .define("ENABLE_MYST"),
          .define("ENABLE_MYSTME"),
          .define("ENABLE_MORTEVIELLE"),
          .define("ENABLE_MTROPOLIS"),
          .define("ENABLE_MYST3"),
          .define("ENABLE_NANCY"),
          .define("ENABLE_NEVERHOOD"),
          .define("ENABLE_NGI"),
          .define("ENABLE_PARALLACTION"),
          .define("ENABLE_PEGASUS"),
          .define("ENABLE_PETKA"),
          .define("ENABLE_PINK"),
          .define("ENABLE_PLUMBERS"),
          .define("ENABLE_PRINCE"),
          .define("ENABLE_PRIVATE"),
          .define("ENABLE_QDENGINE"),
          .define("ENABLE_QUEEN"),
          .define("ENABLE_SAGA"),
          .define("ENABLE_IHNM"),
          .define("ENABLE_SAGA2"),
          .define("ENABLE_SCI"),
          .define("ENABLE_SCI32"),
          .define("ENABLE_SHERLOCK"),
          .define("ENABLE_SKY"),
          .define("ENABLE_STARK"),
          .define("ENABLE_SUPERNOVA"),
          .define("ENABLE_SWORD1"),
          .define("ENABLE_SWORD2"),
          .define("ENABLE_SWORD25"),
          .define("ENABLE_TEENAGENT"),
          .define("ENABLE_TETRAEDGE"),
          .define("ENABLE_TINSEL"),
          .define("ENABLE_TITANIC"),
          .define("ENABLE_TOLTECS"),
          .define("ENABLE_TONY"),
          .define("ENABLE_TOON"),
          .define("ENABLE_TOUCHE"),
          .define("ENABLE_TRECISION"),
          .define("ENABLE_TSAGE"),
          .define("ENABLE_RINGWORLD"),
          .define("ENABLE_BLUEFORCE"),
          .define("ENABLE_RINGWORLD2"),
          .define("ENABLE_TUCKER"),
          .define("ENABLE_TWINE"),
          .define("ENABLE_TWP"),
          .define("ENABLE_ULTIMA"),
          .define("ENABLE_ULTIMA4"),
          .define("ENABLE_ULTIMA6"),
          .define("ENABLE_ULTIMA8"),
          .define("ENABLE_VCRUISE"),
          .define("ENABLE_VOYEUR"),
          .define("ENABLE_WINTERMUTE"),
          .define("ENABLE_FOXTAIL"),
          .define("ENABLE_HEROCRAFT"),
          .define("ENABLE_ZVISION"),
          .define("DETECTION_STATIC"),
          .define("POSIX"),
          .define("USE_SDL2", .when(platforms: [.macOS])),
          .define("USE_GLAD"),
          .define("CONFIG_H"),
          .define("UNIX"),
          .define("HAS_FSEEKO_OFFT_64"),
          .define("SCUMMVM"),
          .define("RELEASE_BUILD"),
          .define("IPHONE", .when(platforms: [.iOS, .tvOS])),
          .define("IPHONE_IOS7", .when(platforms: [.iOS, .tvOS])),
          .define("IPHONE_TVOS", .when(platforms: [.tvOS])),
          .define("WITHOUT_SDL", .when(platforms: [.iOS, .tvOS])),
          .define("SCUMMVM_NEON", .when(platforms: [.iOS, .tvOS])),
          .define("SDL_BACKEND", .when(platforms: [.macOS])),
          .define("MACOSX", .when(platforms: [.macOS])),
        ],
        linkerSettings: [
          .linkedLibrary("c++"),
          .linkedLibrary("z"),
          .linkedLibrary("iconv"),
          .linkedFramework("AudioToolbox"),
          .linkedFramework("CoreAudio"),
          .linkedFramework("CoreFoundation"),
          .linkedFramework("CoreGraphics"),
          .linkedFramework("CoreMIDI"),
          .linkedFramework("Foundation"),
          .linkedFramework("GameController"),
          .linkedFramework("QuartzCore"),
          .linkedFramework("Security"),
          .linkedFramework("SystemConfiguration"),
          .linkedFramework("OpenGLES", .when(platforms: [.iOS, .tvOS])),
          .linkedFramework("UIKit", .when(platforms: [.iOS, .tvOS])),
          .linkedLibrary("lber", .when(platforms: [.macOS])),
          .linkedLibrary("ldap", .when(platforms: [.macOS])),
          .linkedFramework("AppKit", .when(platforms: [.macOS])),
          .linkedFramework("OpenGL", .when(platforms: [.macOS])),
          .linkedFramework("Metal", .when(platforms: [.macOS])),
          .linkedFramework("CoreHaptics", .when(platforms: [.macOS])),
          .linkedFramework("ForceFeedback", .when(platforms: [.macOS])),
          .linkedFramework("AudioUnit", .when(platforms: [.macOS])),
          .linkedFramework("Cocoa", .when(platforms: [.macOS])),
          .linkedFramework("Carbon", .when(platforms: [.macOS])),
          .linkedFramework("ApplicationServices", .when(platforms: [.macOS])),
          .linkedFramework("IOKit", .when(platforms: [.macOS])),
        ]
      ),
      .target(
        name: "ScummVMmacOS",
        dependencies: [
          "ScummVMEngine"
        ],
        path: ".",
        exclude: [
          // Prevent implicit resource discovery from upstream distribution payload.
          "scummvm/dists"
        ],
        sources: [
          "Sources/ScummVMmacOS/ScummVMEngine.mm",
          "Sources/ScummVMmacOS/ScummVMAppContext.mm",
          "scummvm/backends/graphics/sdl/sdl-graphics.cpp",
          "scummvm/backends/graphics/openglsdl/openglsdl-graphics.cpp",
          "scummvm/backends/graphics/surfacesdl/surfacesdl-graphics.cpp",
          "scummvm/backends/imgui/backends/imgui_impl_sdl2.cpp",
          "scummvm/backends/imgui/backends/imgui_impl_sdlrenderer2.cpp",
          "scummvm/backends/platform/sdl/sdl-window.cpp",
          "scummvm/backends/platform/sdl/sdl.cpp",
          "scummvm/backends/platform/sdl/posix/posix.cpp",
          "scummvm/backends/platform/sdl/macosx/appmenu_osx.mm",
          "scummvm/backends/platform/sdl/macosx/macosx-touchbar.mm",
          "scummvm/backends/platform/sdl/macosx/macosx-window.mm",
          "scummvm/backends/platform/sdl/macosx/macosx.cpp",
          "scummvm/backends/platform/sdl/macosx/macosx_osys_misc.mm",
          "scummvm/backends/platform/sdl/macosx/macosx_wrapper.mm",
        ],
        resources: [
          // Only copy the Sparkle DSA key; copying the full macOS app template
          // embeds nested Info.plist files that fail App Store/TestFlight validation.
          .copy("scummvm/dists/macosx/dsa_pub.pem")
        ],
        publicHeadersPath: "Sources/ScummVMmacOS/include",
        cSettings: [
          .headerSearchPath("Sources/ScummVMmacOS"),
          .headerSearchPath("Sources/ScummVMEngineOverrides"),
          .unsafeFlags(["-fno-objc-arc"]),
          .unsafeFlags(["-include", "ScummVMObjCYesNoConsts.h"]),
        ],
        cxxSettings: [
          .headerSearchPath("Sources/ScummVMmacOS"),
          .headerSearchPath("Sources/ScummVMEngineOverrides"),
          .headerSearchPath("scummvm"),
          .headerSearchPath("scummvm/engines"),
          .headerSearchPath("scummvm/backends/platform/sdl/macosx"),
          .unsafeFlags(["-include", "ScummVMObjCYesNoConsts.h"]),
          .define("ENABLE_WME3D"),
          .define("USE_ZLIB"),
          .define("USE_MAD"),
          .define("USE_FRIBIDI"),
          .define("USE_OGG"),
          .define("USE_VORBIS"),
          .define("USE_FLAC"),
          .define("USE_PNG"),
          .define("USE_GIF"),
          .define("USE_FAAD"),
          .define("USE_MIKMOD"),
          .define("USE_MPEG2"),
          .define("USE_THEORADEC"),
          .define("USE_FREETYPE2"),
          .define("USE_JPEG"),
          .define("USE_FLUIDSYNTH"),
          .define("USE_LIBCURL"),
          .define("USE_SDL_NET"),
          .define("USE_BINK"),
          .define("USE_SCALERS"),
          .define("USE_HQ_SCALERS"),
          .define("USE_EDGE_SCALERS"),
          .define("USE_ASPECT"),
          .define("USE_RGB_COLOR"),
          .define("USE_HIGHRES"),
          .define("USE_MT32EMU"),
          .define("USE_OPENGL"),
          .define("USE_OPENGL_GAME"),
          .define("USE_OPENGL_SHADERS"),
          .define("USE_CLOUD"),
          .define("USE_ENET"),
          .define("USE_TRANSLATION"),
          .define("USE_SYSDIALOGS"),
          .define("USE_DETECTLANG"),
          .define("BUILTIN_RESOURCES"),
          .define("USE_DETECTION_FEATURES_STATIC"),
          .define("USE_FMTOWNS_PC98_AUDIO"),
          .define("USE_HNM"),
          .define("USE_INDEO3"),
          .define("USE_INDEO45"),
          .define("USE_LUA"),
          .define("USE_MIDI"),
          .define("USE_SID_AUDIO"),
          .define("USE_TINYGL"),
          .define("USE_UNIVERSALTRACKER"),
          .define("USE_VGMTRANS_AUDIO"),
          .define("ENABLE_SCUMM"),
          .define("ENABLE_SCUMM_7_8"),
          .define("ENABLE_HE"),
          .define("ENABLE_ACCESS"),
          .define("ENABLE_ADL"),
          .define("ENABLE_AGI"),
          .define("ENABLE_AGOS"),
          .define("ENABLE_AGOS2"),
          .define("ENABLE_AGS"),
          .define("ENABLE_ASYLUM"),
          .define("ENABLE_BBVS"),
          .define("ENABLE_BLADERUNNER"),
          .define("ENABLE_BURIED"),
          .define("ENABLE_CGE"),
          .define("ENABLE_CGE2"),
          .define("ENABLE_CHEWY"),
          .define("ENABLE_CINE"),
          .define("ENABLE_COMPOSER"),
          .define("ENABLE_CRAB"),
          .define("ENABLE_CRUISE"),
          .define("ENABLE_CRYOMNI3D"),
          .define("ENABLE_VERSAILLES"),
          .define("ENABLE_DARKSEED"),
          .define("ENABLE_DGDS"),
          .define("ENABLE_DIRECTOR"),
          .define("ENABLE_DRACI"),
          .define("ENABLE_DRAGONS"),
          .define("ENABLE_DRASCULA"),
          .define("ENABLE_DREAMWEB"),
          .define("ENABLE_EFH"),
          .define("ENABLE_FREESCAPE"),
          .define("ENABLE_GLK"),
          .define("ENABLE_GNAP"),
          .define("ENABLE_GOB"),
          .define("ENABLE_GRIFFON"),
          .define("ENABLE_GRIM"),
          .define("ENABLE_GROOVIE"),
          .define("ENABLE_GROOVIE2"),
          .define("ENABLE_HADESCH"),
          .define("ENABLE_HDB"),
          .define("ENABLE_HOPKINS"),
          .define("ENABLE_HUGO"),
          .define("ENABLE_HYPNO"),
          .define("ENABLE_ILLUSIONS"),
          .define("ENABLE_KINGDOM"),
          .define("ENABLE_KYRA"),
          .define("ENABLE_LOL"),
          .define("ENABLE_EOB"),
          .define("ENABLE_LAB"),
          .define("ENABLE_LURE"),
          .define("ENABLE_M4"),
          .define("ENABLE_MADE"),
          .define("ENABLE_MADS"),
          .define("ENABLE_MM"),
          .define("ENABLE_MM1"),
          .define("ENABLE_XEEN"),
          .define("ENABLE_MOHAWK"),
          .define("ENABLE_RIVEN"),
          .define("ENABLE_MYST"),
          .define("ENABLE_MYSTME"),
          .define("ENABLE_MORTEVIELLE"),
          .define("ENABLE_MTROPOLIS"),
          .define("ENABLE_MYST3"),
          .define("ENABLE_NANCY"),
          .define("ENABLE_NEVERHOOD"),
          .define("ENABLE_NGI"),
          .define("ENABLE_PARALLACTION"),
          .define("ENABLE_PEGASUS"),
          .define("ENABLE_PETKA"),
          .define("ENABLE_PINK"),
          .define("ENABLE_PLUMBERS"),
          .define("ENABLE_PRINCE"),
          .define("ENABLE_PRIVATE"),
          .define("ENABLE_QDENGINE"),
          .define("ENABLE_QUEEN"),
          .define("ENABLE_SAGA"),
          .define("ENABLE_IHNM"),
          .define("ENABLE_SAGA2"),
          .define("ENABLE_SCI"),
          .define("ENABLE_SCI32"),
          .define("ENABLE_SHERLOCK"),
          .define("ENABLE_SKY"),
          .define("ENABLE_STARK"),
          .define("ENABLE_SUPERNOVA"),
          .define("ENABLE_SWORD1"),
          .define("ENABLE_SWORD2"),
          .define("ENABLE_SWORD25"),
          .define("ENABLE_TEENAGENT"),
          .define("ENABLE_TETRAEDGE"),
          .define("ENABLE_TINSEL"),
          .define("ENABLE_TITANIC"),
          .define("ENABLE_TOLTECS"),
          .define("ENABLE_TONY"),
          .define("ENABLE_TOON"),
          .define("ENABLE_TOUCHE"),
          .define("ENABLE_TRECISION"),
          .define("ENABLE_TSAGE"),
          .define("ENABLE_RINGWORLD"),
          .define("ENABLE_BLUEFORCE"),
          .define("ENABLE_RINGWORLD2"),
          .define("ENABLE_TUCKER"),
          .define("ENABLE_TWINE"),
          .define("ENABLE_TWP"),
          .define("ENABLE_ULTIMA"),
          .define("ENABLE_ULTIMA4"),
          .define("ENABLE_ULTIMA6"),
          .define("ENABLE_ULTIMA8"),
          .define("ENABLE_VCRUISE"),
          .define("ENABLE_VOYEUR"),
          .define("ENABLE_WINTERMUTE"),
          .define("ENABLE_FOXTAIL"),
          .define("ENABLE_HEROCRAFT"),
          .define("ENABLE_ZVISION"),
          .define("POSIX"),
          .define("DETECTION_STATIC"),
          .define("USE_GLAD"),
          .define("CONFIG_H"),
          .define("UNIX"),
          .define("HAS_FSEEKO_OFFT_64"),
          .define("SCUMMVM"),
          .define("RELEASE_BUILD"),
          .define("SDL_BACKEND", .when(platforms: [.macOS])),
          .define("MACOSX", .when(platforms: [.macOS])),
          .unsafeFlags(["-fno-objc-arc"]),
        ]
      ),
      .target(
        name: "ScummVMiOS",
        dependencies: [
          "ScummVMEngine"
        ],
        path: ".",
        exclude: [
          // Prevent implicit resource discovery from upstream distribution payload.
          "scummvm/dists"
        ],
        sources: [
          "Sources/ScummVMiOS/ScummVMEngine.mm",
          "Sources/ScummVMiOS/ScummVMAppContext.mm",
          "Sources/ScummVMiOS/ScummVMAppDelegate.mm",
          "Sources/ScummVMiOS/ScummVMIOSBridge.cpp",
          "scummvm/backends/graphics/ios/ios-graphics.cpp",
          "scummvm/backends/graphics/ios/renderbuffer.cpp",
          "Sources/ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_main.cpp",
          "Sources/ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_events.cpp",
          "Sources/ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_sound.cpp",
          "Sources/ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_video.mm",
          "scummvm/backends/platform/ios7/ios7_osys_misc.mm",
          "scummvm/backends/platform/ios7/ios7_misc.mm",
          "scummvm/backends/platform/ios7/ios7_options.mm",
          "Sources/ScummVMEngineOverrides/backends/platform/ios7/ios7_video.mm",
          "scummvm/backends/platform/ios7/ios7_keyboard.mm",
          "scummvm/backends/platform/ios7/ios7_scummvm_view_controller.mm",
          "scummvm/backends/platform/ios7/ios7_game_controller.mm",
          "scummvm/backends/platform/ios7/ios7_touch_controller.mm",
          "scummvm/backends/platform/ios7/ios7_mouse_controller.mm",
          "scummvm/backends/platform/ios7/ios7_gamepad_controller.mm",
        ],
        resources: [
          // Platform-specific metadata/assets
          .process("scummvm/dists/ios7/Images.xcassets"),
          .copy("scummvm/dists/ios7/PrivacyInfo.xcprivacy"),
        ],
        publicHeadersPath: "Sources/ScummVMiOS/include",
        cSettings: [
          .headerSearchPath("Sources/ScummVMiOS/include"),
          .headerSearchPath("Sources/ScummVMiOS"),
          .headerSearchPath("Sources/ScummVMEngineOverrides"),
          .unsafeFlags(["-fno-objc-arc"]),
          .unsafeFlags(["-include", "ScummVMObjCYesNoConsts.h"]),
        ],
        cxxSettings: [
          .headerSearchPath("Sources/ScummVMiOS/include"),
          .headerSearchPath("Sources/ScummVMiOS"),
          .headerSearchPath("Sources/ScummVMEngineOverrides"),
          .headerSearchPath("scummvm"),
          .headerSearchPath("scummvm/engines"),
          .headerSearchPath("scummvm/backends/platform/ios7"),
          .unsafeFlags(["-include", "ScummVMObjCYesNoConsts.h"]),
          .define("ENABLE_WME3D"),
          .define("USE_ZLIB"),
          .define("USE_MAD"),
          .define("USE_FRIBIDI"),
          .define("USE_OGG"),
          .define("USE_VORBIS"),
          .define("USE_FLAC"),
          .define("USE_PNG"),
          .define("USE_GIF"),
          .define("USE_FAAD"),
          .define("USE_MIKMOD"),
          .define("USE_MPEG2"),
          .define("USE_THEORADEC"),
          .define("USE_FREETYPE2"),
          .define("USE_JPEG"),
          .define("USE_FLUIDSYNTH"),
          .define("USE_LIBCURL"),
          .define("USE_SDL_NET"),
          .define("USE_BINK"),
          .define("USE_SCALERS"),
          .define("USE_HQ_SCALERS"),
          .define("USE_EDGE_SCALERS"),
          .define("USE_ASPECT"),
          .define("USE_RGB_COLOR"),
          .define("USE_HIGHRES"),
          .define("USE_MT32EMU"),
          .define("USE_OPENGL"),
          .define("USE_OPENGL_GAME"),
          .define("USE_OPENGL_SHADERS"),
          .define("USE_CLOUD"),
          .define("USE_ENET"),
          .define("USE_TRANSLATION"),
          .define("USE_SYSDIALOGS"),
          .define("USE_DETECTLANG"),
          .define("USE_DETECTION_FEATURES_STATIC"),
          .define("USE_FMTOWNS_PC98_AUDIO"),
          .define("USE_HNM"),
          .define("USE_INDEO3"),
          .define("USE_INDEO45"),
          .define("USE_LUA"),
          .define("USE_MIDI"),
          .define("USE_SID_AUDIO"),
          .define("USE_TINYGL"),
          .define("USE_UNIVERSALTRACKER"),
          .define("USE_VGMTRANS_AUDIO"),
          .define("ENABLE_SCUMM"),
          .define("ENABLE_SCUMM_7_8"),
          .define("ENABLE_HE"),
          .define("ENABLE_ACCESS"),
          .define("ENABLE_ADL"),
          .define("ENABLE_AGI"),
          .define("ENABLE_AGOS"),
          .define("ENABLE_AGOS2"),
          .define("ENABLE_AGS"),
          .define("ENABLE_ASYLUM"),
          .define("ENABLE_BBVS"),
          .define("ENABLE_BLADERUNNER"),
          .define("ENABLE_BURIED"),
          .define("ENABLE_CGE"),
          .define("ENABLE_CGE2"),
          .define("ENABLE_CHEWY"),
          .define("ENABLE_CINE"),
          .define("ENABLE_COMPOSER"),
          .define("ENABLE_CRAB"),
          .define("ENABLE_CRUISE"),
          .define("ENABLE_CRYOMNI3D"),
          .define("ENABLE_VERSAILLES"),
          .define("ENABLE_DARKSEED"),
          .define("ENABLE_DGDS"),
          .define("ENABLE_DIRECTOR"),
          .define("ENABLE_DRACI"),
          .define("ENABLE_DRAGONS"),
          .define("ENABLE_DRASCULA"),
          .define("ENABLE_DREAMWEB"),
          .define("ENABLE_EFH"),
          .define("ENABLE_FREESCAPE"),
          .define("ENABLE_GLK"),
          .define("ENABLE_GNAP"),
          .define("ENABLE_GOB"),
          .define("ENABLE_GRIFFON"),
          .define("ENABLE_GRIM"),
          .define("ENABLE_GROOVIE"),
          .define("ENABLE_GROOVIE2"),
          .define("ENABLE_HADESCH"),
          .define("ENABLE_HDB"),
          .define("ENABLE_HOPKINS"),
          .define("ENABLE_HUGO"),
          .define("ENABLE_HYPNO"),
          .define("ENABLE_ILLUSIONS"),
          .define("ENABLE_KINGDOM"),
          .define("ENABLE_KYRA"),
          .define("ENABLE_LOL"),
          .define("ENABLE_EOB"),
          .define("ENABLE_LAB"),
          .define("ENABLE_LURE"),
          .define("ENABLE_M4"),
          .define("ENABLE_MADE"),
          .define("ENABLE_MADS"),
          .define("ENABLE_MM"),
          .define("ENABLE_MM1"),
          .define("ENABLE_XEEN"),
          .define("ENABLE_MOHAWK"),
          .define("ENABLE_RIVEN"),
          .define("ENABLE_MYST"),
          .define("ENABLE_MYSTME"),
          .define("ENABLE_MORTEVIELLE"),
          .define("ENABLE_MTROPOLIS"),
          .define("ENABLE_MYST3"),
          .define("ENABLE_NANCY"),
          .define("ENABLE_NEVERHOOD"),
          .define("ENABLE_NGI"),
          .define("ENABLE_PARALLACTION"),
          .define("ENABLE_PEGASUS"),
          .define("ENABLE_PETKA"),
          .define("ENABLE_PINK"),
          .define("ENABLE_PLUMBERS"),
          .define("ENABLE_PRINCE"),
          .define("ENABLE_PRIVATE"),
          .define("ENABLE_QDENGINE"),
          .define("ENABLE_QUEEN"),
          .define("ENABLE_SAGA"),
          .define("ENABLE_IHNM"),
          .define("ENABLE_SAGA2"),
          .define("ENABLE_SCI"),
          .define("ENABLE_SCI32"),
          .define("ENABLE_SHERLOCK"),
          .define("ENABLE_SKY"),
          .define("ENABLE_STARK"),
          .define("ENABLE_SUPERNOVA"),
          .define("ENABLE_SWORD1"),
          .define("ENABLE_SWORD2"),
          .define("ENABLE_SWORD25"),
          .define("ENABLE_TEENAGENT"),
          .define("ENABLE_TETRAEDGE"),
          .define("ENABLE_TINSEL"),
          .define("ENABLE_TITANIC"),
          .define("ENABLE_TOLTECS"),
          .define("ENABLE_TONY"),
          .define("ENABLE_TOON"),
          .define("ENABLE_TOUCHE"),
          .define("ENABLE_TRECISION"),
          .define("ENABLE_TSAGE"),
          .define("ENABLE_RINGWORLD"),
          .define("ENABLE_BLUEFORCE"),
          .define("ENABLE_RINGWORLD2"),
          .define("ENABLE_TUCKER"),
          .define("ENABLE_TWINE"),
          .define("ENABLE_TWP"),
          .define("ENABLE_ULTIMA"),
          .define("ENABLE_ULTIMA4"),
          .define("ENABLE_ULTIMA6"),
          .define("ENABLE_ULTIMA8"),
          .define("ENABLE_VCRUISE"),
          .define("ENABLE_VOYEUR"),
          .define("ENABLE_WINTERMUTE"),
          .define("ENABLE_FOXTAIL"),
          .define("ENABLE_HEROCRAFT"),
          .define("ENABLE_ZVISION"),
          .define("POSIX"),
          .define("DETECTION_STATIC"),
          .define("USE_GLAD"),
          .define("CONFIG_H"),
          .define("UNIX"),
          .define("HAS_FSEEKO_OFFT_64"),
          .define("SCUMMVM"),
          .define("RELEASE_BUILD"),
          .define("IPHONE", .when(platforms: [.iOS, .tvOS])),
          .define("IPHONE_IOS7", .when(platforms: [.iOS, .tvOS])),
          .define("IPHONE_TVOS", .when(platforms: [.tvOS])),
          .define("WITHOUT_SDL", .when(platforms: [.iOS, .tvOS])),
          .define("SCUMMVM_NEON", .when(platforms: [.iOS, .tvOS])),
          .unsafeFlags(["-fno-objc-arc"]),
        ]
      ),
      .target(
        name: "ScummVMtvOS",
        dependencies: [
          "ScummVMiOS"
        ],
        resources: tvOSResources
      ),

      scummVMBinaryTarget(
        name: "a52",
        checksum: "d389d7055deb36bf779853d51f6dbd653d91dbcb7fee382786b969de8b2081db"
      ),
      scummVMBinaryTarget(
        name: "bz2",
        checksum: "2b16e6713db951acb6e06da11145469115a6f0650237d1787a8f3e7f0bdc12ff"
      ),
      scummVMBinaryTarget(
        name: "curl",
        checksum: "6e6977bad5c44a97712655c76fb81eb56c02aab3ca8c29c728bf3dd0269df8dd"
      ),
      scummVMBinaryTarget(
        name: "faad",
        checksum: "ec84329b992724c799ad8aee1071c5b8f6382d8c540e967785f96edf9bb87672"
      ),
      scummVMBinaryTarget(
        name: "ffi",
        checksum: "0ada0e580efc9e5c7ca0c17a04499bd25654709dfc91731fd835ec26b04815ad"
      ),
      scummVMBinaryTarget(
        name: "FLAC",
        checksum: "aa3c469bfb104f6bb8717d6033cda99c27f16d16031e19e1e2491678d8bb94b6"
      ),
      scummVMBinaryTarget(
        name: "fluidsynth",
        checksum: "864ae3f5eaef39c43ceb8b9ad7cfa242010ad20d7756f3d2340b66c9b0e18fa4"
      ),
      scummVMBinaryTarget(
        name: "freetype",
        checksum: "71c6c65222daeaf345bbb316fe70423d0db369f0820cdb81dabe68287463c78e"
      ),
      scummVMBinaryTarget(
        name: "fribidi",
        checksum: "15bf1673a3e706aa46f5a71eae585be3a20cf2402e2d03340506d05df47c18e0"
      ),
      scummVMBinaryTarget(
        name: "gif",
        checksum: "a0463ef3ba12c6fbafe223d2ae063d43dd56c94dbbb8e36f041c6c5072085557"
      ),
      scummVMBinaryTarget(
        name: "glib-2.0",
        checksum: "41a33cdc196bffd972752cd0c16b06b5daf60fe4aa1b123f2e0d08489ea22040"
      ),
      scummVMBinaryTarget(
        name: "intl",
        checksum: "bc9c91956f78d0830b653efc98a38f96adfcc2a049b6bb59f720e401efe82bf1"
      ),
      scummVMBinaryTarget(
        name: "jpeg",
        checksum: "6a83eef6a7c885e05fedf9870538396a743d7dd9ded6b637dddc40d09c82d749"
      ),
      scummVMBinaryTarget(
        name: "mad",
        checksum: "bf040e3ff3d11a612d70d7aa37275d0b1c1a86549ed9178ec46b693ac7c92048"
      ),
      scummVMBinaryTarget(
        name: "mikmod",
        checksum: "363f6cb9a6b269636245b852f2f15242bef3255b69b9bea9ed2a1628ba628bd7"
      ),
      scummVMBinaryTarget(
        name: "mpeg2",
        checksum: "4b883dba8c5ef81669a5ee5b8bcfc773d2c2c1fdd17a750d0bbcabcdcdbb7050"
      ),
      scummVMBinaryTarget(
        name: "ogg",
        checksum: "d78d39567e53f94fdbee93d21065d07b96f35f099e6a5c17a5c1d5f58dfbb445"
      ),
      scummVMBinaryTarget(
        name: "png",
        checksum: "a27e1a1a7b9d67dc956f5ee8ab83b047b408b1e6b6e1f06f6f52883dfe62f634"
      ),
      scummVMBinaryTarget(
        name: "SDL2_net",
        checksum: "eb50388fa0aa5a23a1c6476d7bf124003382e344248d2ac6f0dbe4dc010b2c50"
      ),
      scummVMBinaryTarget(
        name: "SDL2",
        checksum: "2e2e591f2c1d7af4b465f49ccbe5ddd7f77c14ee1b803027b28a4dc992863f71"
      ),
      scummVMBinaryTarget(
        name: "theoradec",
        checksum: "eddf9491aa3042499821a3152e2f4f19f7adf544a4b48a02272b39a423ed674f"
      ),
      scummVMBinaryTarget(
        name: "vorbis",
        checksum: "b33a2c7d80f2ac71990ee7a2c79c3a986adb43d39f16520d6d3a4a9fcfad4a30"
      ),
      scummVMBinaryTarget(
        name: "vorbisfile",
        checksum: "96f5ef4d769390464a8b7a93328985d799bd26a5d583432778fecc5ba8557e67"
      ),
      scummVMBinaryTarget(
        name: "vpx",
        checksum: "8777c659010e27e158357dde6d418a00af9670df50a608e02b2264e9d61b8a3f"
      ),
  ]
  : [
    scummVMEngineBinaryTarget(
      name: "ScummVMiOS",
      checksum: engineChecksumiOS
    ),
    scummVMEngineBinaryTarget(
      name: "ScummVMtvOS",
      checksum: engineChecksumtvOS
    ),
    scummVMEngineBinaryTarget(
      name: "ScummVMmacOS",
      checksum: engineChecksummacOS
    ),
  ]

let package = Package(
  name: "swift-scummvm",
  platforms: [
    .iOS(.v17), .tvOS(.v17), .macOS(.v15),
  ],
  products: [
    .library(
      name: "ScummVM",
      targets: ["ScummVM"]
    ),
    .executable(
      name: "ScummVMApp",
      targets: ["ScummVMApp"]
    ),
    .library(
      name: "ScummVMiOS",
      targets: ["ScummVMiOS"]
    ),
    .library(
      name: "ScummVMmacOS",
      targets: ["ScummVMmacOS"]
    ),
    .library(
      name: "ScummVMtvOS",
      targets: ["ScummVMtvOS"]
    ),
  ],
  dependencies: [
    .package(url: "https://github.com/weichsel/ZIPFoundation.git", from: "0.9.20")
  ],
  targets: [
    .target(
      name: "ScummVM",
      dependencies: [
        .product(name: "ZIPFoundation", package: "ZIPFoundation"),
        .target(name: "ScummVMmacOS", condition: .when(platforms: [.macOS])),
        .target(name: "ScummVMiOS", condition: .when(platforms: [.iOS])),
        .target(name: "ScummVMtvOS", condition: .when(platforms: [.tvOS])),
      ]
    ),
    .executableTarget(
      name: "ScummVMApp",
      dependencies: [
        .target(name: "ScummVM", condition: .when(platforms: [.macOS]))
      ]
    ),
    .testTarget(
      name: "ScummVMTests",
      dependencies: [
        "ScummVM",
        // Only macOS runs `swift test` in CI (see ci.yml's build-binary job), and
        // only against the prebuilt engine - exercising the ObjC facade directly
        // requires this import on that platform.
        .target(name: "ScummVMmacOS", condition: .when(platforms: [.macOS])),
      ]
    ),
  ] + engineTargets,
  cLanguageStandard: .c11,
  cxxLanguageStandard: .cxx17
)

func scummVMBinaryTarget(
  name: String,
  checksum: String,
  baseURL: String = binaryBaseURL
) -> Target {
  let url = "\(baseURL)/\(name).xcframework.zip"
  return .binaryTarget(
    name: name,
    url: url,
    checksum: checksum)
}

func scummVMEngineBinaryTarget(name: String, checksum: String) -> Target {
  if let localEngineArtifactsPath {
    return .binaryTarget(
      name: name,
      path: "\(localEngineArtifactsPath)/\(name).xcframework"
    )
  }
  return scummVMBinaryTarget(
    name: name,
    checksum: checksum,
    baseURL: engineBinaryBaseURL
  )
}
