// swift-tools-version:6.0
import Foundation
import PackageDescription

let binaryBaseURL = "https://github.com/dooop/scummvm/releases/download/0.2.0"

// Prebuilt ScummVM engine + platform glue. Published by .github/workflows/release-engine.yml;
// bump the tag and all three checksums together when a new engine build ships.
let engineBinaryBaseURL = "https://github.com/dooop/scummvm/releases/download/0.6.1"
let engineChecksumiOS = "df50a3627edbdf7984de8c30efdb6636e0b78b1b673e109ec17e7ed5bcf33938"
let engineChecksumtvOS = "ee604164cab618cdad4f589accfdc5095b14e1dd5917ffb28c8b87118ce1168d"
let engineChecksummacOS = "1bb64d01bb47d31f1c612ac20ac791c8457fb6fc978dfdeabea2ad4a41bb4c56"
// Internal release validation can point binary mode at freshly assembled local
// XCFrameworks before they are published. The path is relative to the package root.
let localEngineArtifactsPath = ProcessInfo.processInfo.environment["SCUMMVM_ENGINE_ARTIFACTS_DIR"]

// Consumers link the prebuilt engine: ~7,700 upstream translation units and the
// 534 MB submodule checkout drop out of their build entirely.
//
// Set SCUMMVM_BUILD_FROM_SOURCE=1 to compile the engine from scummvm
// instead - required when touching engine code, overrides or the platform glue, and
// used by the release pipeline itself. SwiftPM caches the parsed manifest by content,
// not by environment, so run `swift package reset` when flipping the switch.
let buildEngineFromSource = ProcessInfo.processInfo.environment["SCUMMVM_BUILD_FROM_SOURCE"] != nil

// Source-mode-only resource rules for the ScummVMtvOS re-export target (see its
// definition in engineTargets below). Binary mode ships a real ScummVMtvOS
// XCFramework instead, with these assets already baked into its Resources.
let tvOSResources: [Resource] = [
  .process("../ScummVMEngine/dists/tvos/Images.xcassets"),
  .copy("../ScummVMEngine/dists/tvos/PrivacyInfo.xcprivacy"),
]

// Engine + platform glue: compiled from the submodule in source mode, downloaded as
// prebuilt dynamic-framework XCFrameworks otherwise. The two modes are mutually
// exclusive, so the binary targets reuse the source target names and every dependent
// target's dependency list stays identical either way.
//
// The prebuilt frameworks are dynamic and link the third-party static libraries and
// system frameworks into themselves, and they carry the runtime payload in their own
// Resources directory. In binary mode none of that appears in the consumer's graph -
// they resolve two artifacts instead of twenty-six, with no submodule in sight.
let engineTargets: [Target] =
  buildEngineFromSource
  ? [
    .target(
      name: "ScummVMEngine",
      dependencies: [
        "a52", "bz2", "curl", "faad", "ffi", "FLAC", "fluidsynth",
        "freetype", "fribidi", "gif", "glib-2.0", "intl", "jpeg",
        "mad", "mikmod", "mpeg2", "ogg", "png", "SDL2_net",
        "theoradec", "vorbis", "vorbisfile", "vpx",
        .target(name: "SDL2", condition: .when(platforms: [.macOS])),
      ],
      path: "swift/Sources",
      exclude: [
        // Other targets (this target should only build engine + overrides).
        "ScummVM",
        "ScummVMApp",
        "ScummVMiOS",
        "ScummVMmacOS",
        "ScummVMtvOS",
        // Upstream non-runtime directories.
        "ScummVMEngine/devtools",
        "ScummVMEngine/dists",
        "ScummVMEngine/test",
        "ScummVMEngine/doc",
        "ScummVMEngine/po",
        "ScummVMEngine/icons",
        "ScummVMEngine/LICENSES",
        // Keep runtime payload on explicit resource copy rules (avoid auto resource duplication)
        "ScummVMEngine/gui/themes",
        // Prevent duplicate asset names (iOS + tvOS variants share filenames).
        "ScummVMEngine/dists/tvos",
        // Upstream files excluded from this target
        "ScummVMEngine/engines/ags/tests",
        "ScummVMEngine/engines/glk/adrift/sxstubs.cpp",
        "ScummVMEngine/engines/glk/adrift/sxscript.cpp",
        "ScummVMEngine/backends/platform/android",
        "ScummVMEngine/backends/platform/ios7",
        // macOS SDL backend is built in ScummVMmacOS target
        "ScummVMEngine/backends/platform/sdl",
        "ScummVMEngine/backends/platform/psp",
        "ScummVMEngine/backends/platform/3ds",
        "ScummVMEngine/backends/platform/maemo",
        "ScummVMEngine/backends/platform/n64",
        "ScummVMEngine/backends/platform/openpandora",
        "ScummVMEngine/backends/platform/samsungtv",
        "ScummVMEngine/backends/platform/wii",
        "ScummVMEngine/backends/platform/null",
        "ScummVMEngine/backends/platform/libretro",
        "ScummVMEngine/backends/platform/libretro/src/libretro-threads.cpp",
        "ScummVMEngine/backends/events/maemosdl",
        "ScummVMEngine/backends/events/openpandora",
        "ScummVMEngine/backends/events/ps3sdl",
        "ScummVMEngine/backends/events/psp2sdl",
        "ScummVMEngine/backends/events/riscossdl",
        "ScummVMEngine/backends/events/samsungtvsdl",
        "ScummVMEngine/backends/events/switchsdl",
        "ScummVMEngine/backends/graphics/maemosdl",
        "ScummVMEngine/backends/graphics/openpandora",
        "ScummVMEngine/backends/graphics/riscossdl",
        "ScummVMEngine/backends/dialogs/amigaos",
        "ScummVMEngine/backends/dialogs/gtk",
        "ScummVMEngine/backends/dialogs/morphos",
        "ScummVMEngine/backends/dialogs/win32",
        "ScummVMEngine/backends/audiocd/linux",
        "ScummVMEngine/backends/audiocd/win32",
        "ScummVMEngine/backends/audiocd/atari",
        "ScummVMEngine/backends/networking/basic/android",
        "ScummVMEngine/backends/networking/http/android",
        "ScummVMEngine/backends/networking/http/emscripten",
        "ScummVMEngine/backends/networking/enet/source/win32.cpp",
        "ScummVMEngine/video/mkv_decoder.cpp",
        // Override to support builds without ENABLE_EVENTRECORDER (e.g. iOS/tvOS)
        "ScummVMEngine/common/recorderfile.cpp",
        "ScummVMEngine/gui/updates-dialog.cpp",
        // Override to support builds without ENABLE_EVENTRECORDER (e.g. iOS/tvOS)
        "ScummVMEngine/gui/recorderdialog.cpp",
        // Override to support builds without ENABLE_EVENTRECORDER (e.g. iOS/tvOS)
        "ScummVMEngine/gui/onscreendialog.cpp",
        // Override: fixes a U32String/String comparison mismatch (pre-existing
        // upstream bug, unrelated to this package's configuration)
        "ScummVMEngine/gui/downloaddlcsdialog.cpp",
        // Override: isImGuiRecorderEnabled() turned into a free function
        // (see override file for why a header-only fix doesn't work here)
        "ScummVMEngine/gui/EventRecorder.cpp",
        "ScummVMEngine/common/updates.cpp",
        "ScummVMEngine/backends/taskbar",
        "ScummVMEngine/backends/fs/android",
        "ScummVMEngine/backends/fs/kolibrios",
        "ScummVMEngine/backends/fs/emscripten",
        "ScummVMEngine/backends/fs/atari",
        "ScummVMEngine/backends/fs/amigaos",
        "ScummVMEngine/backends/fs/devoptab",
        "ScummVMEngine/backends/fs/morphos",
        "ScummVMEngine/backends/fs/n64",
        "ScummVMEngine/backends/fs/ps3",
        "ScummVMEngine/backends/fs/psp",
        "ScummVMEngine/backends/fs/riscos",
        "ScummVMEngine/backends/fs/wii",
        "ScummVMEngine/backends/fs/windows",
        "ScummVMEngine/backends/graphics/sdl",
        "ScummVMEngine/backends/graphics/surfacesdl",
        "ScummVMEngine/backends/graphics/openglsdl",
        "ScummVMEngine/backends/graphics/ios",
        "ScummVMEngine/backends/graphics/android",
        "ScummVMEngine/backends/graphics/opendingux",
        "ScummVMEngine/backends/graphics/miyoo",
        "ScummVMEngine/backends/saves/kolibrios",
        "ScummVMEngine/backends/saves/windows/windows-saves.cpp",
        // Override to support builds without ENABLE_EVENTRECORDER (e.g. iOS/tvOS)
        "ScummVMEngine/backends/saves/recorder/recorder-saves.cpp",
        // x86 SSE/AVX intrinsics – not compilable on ARM
        "ScummVMEngine/graphics/blit/blit-sse2.cpp",
        "ScummVMEngine/graphics/blit/blit-avx2.cpp",
        "ScummVMEngine/graphics/blit/blit-atari.cpp",
        // Generated larryScale code depends on missing generator headers
        "ScummVMEngine/graphics/larryScale_generated.cpp",
        "ScummVMEngine/engines/ags/lib/allegro/surface_sse2.cpp",
        "ScummVMEngine/engines/ags/lib/allegro/surface_avx2.cpp",
        "ScummVMEngine/engines/ags/lib/allegro/fmaths.cpp",
        "ScummVMEngine/engines/titanic/game/transport/exit_pellerator.cpp",
        // ARM32 assembly – incompatible with arm64
        "ScummVMEngine/graphics/scaler/scale2xARM.s",
        "ScummVMEngine/graphics/scaler/Normal2xARM.s",
        "ScummVMEngine/graphics/scaler/downscalerARM.s",
        "ScummVMEngine/engines/grim/movie/codecs/blocky8ARM.s",
        "ScummVMEngine/engines/scumm/gfxARM.s",
        "ScummVMEngine/engines/scumm/smush/codec47ARM.s",
        // M68K assembly (Amiga/Atari) – incompatible with arm64/x86_64
        "ScummVMEngine/engines/scumm/gfxM68K.S",
        "ScummVMEngine/engines/scumm/m68k",
        // Rebel Assault II PSX support: gated upstream behind ENABLE_REBEL2_PSX,
        // which this package does not define; unlike scumm.cpp's own references
        // (properly #ifdef-guarded), these sources reference the gated types
        // unconditionally and fail to compile without the flag.
        "ScummVMEngine/engines/scumm/insane/rebel2/psx",
        // Platform-specific assembly (Atari, DS, Dreamcast)
        "ScummVMEngine/backends/graphics/atari",
        "ScummVMEngine/backends/platform/atari",
        "ScummVMEngine/backends/platform/dc",
        "ScummVMEngine/backends/platform/ds",
        "ScummVMEngine/backends/mixer/atari",
        "ScummVMEngine/backends/mixer/android",
        "ScummVMEngine/backends/mixer/emscriptensdl",
        "ScummVMEngine/backends/midi/camd.cpp",
        "ScummVMEngine/backends/midi/dmedia.cpp",
        "ScummVMEngine/backends/midi/riscos.cpp",
        "ScummVMEngine/backends/midi/sndio.cpp",
        "ScummVMEngine/backends/midi/stmidi.cpp",
        "ScummVMEngine/backends/midi/webmidi.cpp",
        "ScummVMEngine/backends/midi/windows.cpp",
        "ScummVMEngine/backends/mixer/maxmod",
        "ScummVMEngine/backends/mutex/3ds",
        "ScummVMEngine/backends/mutex/wii",
        "ScummVMEngine/backends/plugins/3ds",
        "ScummVMEngine/backends/plugins/ds",
        "ScummVMEngine/backends/plugins/kolibrios",
        "ScummVMEngine/backends/plugins/psp",
        "ScummVMEngine/backends/plugins/psp2",
        "ScummVMEngine/backends/plugins/riscos",
        "ScummVMEngine/backends/plugins/wii",
        "ScummVMEngine/backends/plugins/win32",
        "ScummVMEngine/backends/plugins/atari",
        "ScummVMEngine/backends/plugins/elf",
        "ScummVMEngine/backends/plugins/firebee",
        "ScummVMEngine/backends/plugins/mintelf",
        "ScummVMEngine/backends/printing/win32",
        "ScummVMEngine/backends/text-to-speech/emscripten",
        "ScummVMEngine/backends/text-to-speech/linux",
        "ScummVMEngine/backends/text-to-speech/windows",
        "ScummVMEngine/backends/updates/win32",
        "ScummVMEngine/backends/timer/psp",
        "ScummVMEngine/backends/timer/emscripten",
        // RetroWave hardware OPL3 – requires external library
        "ScummVMEngine/audio/rwopl3.cpp",
        // OPL2LPT/OPL3LPT – requires libieee1284
        "ScummVMEngine/audio/opl2lpt.cpp",
        // ALSA OPL – requires ALSA headers
        "ScummVMEngine/audio/alsa_opl.cpp",
        // nFM hardware OPL boards – requires the external nfm library headers
        // (nfmcore.h/nfmutil.h); gated upstream behind USE_NFM in fmopl.cpp,
        // but this standalone TU includes them unconditionally.
        "ScummVMEngine/audio/nfmopl.cpp",
        // Atari YM2149 chip backend – includes Atari MiNT/TOS system headers
        // unconditionally; gated upstream behind #ifdef ATARI in ym2149.cpp.
        "ScummVMEngine/audio/atari_ym2149.cpp",
        // libsoxr adapter – requires soxr headers
        "ScummVMEngine/audio/softsynth/mt32/srchelper/SoxrAdapter.cpp",
        "ScummVMEngine/audio/softsynth/mt32/srchelper/SoxrAdapter.h",
        // libsamplerate adapter – requires samplerate headers
        "ScummVMEngine/audio/softsynth/mt32/srchelper/SamplerateAdapter.cpp",
        "ScummVMEngine/audio/softsynth/mt32/srchelper/SamplerateAdapter.h",
        // Engine not enabled / missing headers
        "ScummVMEngine/engines/icb",
        // Engine modules disabled by current ENABLE_* selection in Package.swift.
        "ScummVMEngine/engines/agds",
        "ScummVMEngine/engines/alcachofa",
        "ScummVMEngine/engines/alg",
        "ScummVMEngine/engines/avalanche",
        "ScummVMEngine/engines/awe",
        "ScummVMEngine/engines/bolt",
        "ScummVMEngine/engines/chamber",
        "ScummVMEngine/engines/colony",
        "ScummVMEngine/engines/cryo",
        "ScummVMEngine/engines/dm",
        "ScummVMEngine/engines/eem",
        "ScummVMEngine/engines/fool",
        "ScummVMEngine/engines/gamos",
        "ScummVMEngine/engines/got",
        "ScummVMEngine/engines/harvester",
        "ScummVMEngine/engines/hpl1",
        "ScummVMEngine/engines/immortal",
        "ScummVMEngine/engines/lastexpress",
        "ScummVMEngine/engines/lilliput",
        "ScummVMEngine/engines/macs2",
        "ScummVMEngine/engines/macventure",
        "ScummVMEngine/engines/mediastation",
        "ScummVMEngine/engines/mutationofjb",
        "ScummVMEngine/engines/pelrock",
        "ScummVMEngine/engines/phoenixvr",
        "ScummVMEngine/engines/playground3d",
        "ScummVMEngine/engines/sludge",
        "ScummVMEngine/engines/startrek",
        "ScummVMEngine/engines/testbed",
        "ScummVMEngine/engines/tot",
        "ScummVMEngine/engines/wage",
        "ScummVMEngine/engines/watchmaker",
        "ScummVMEngine/engines/waynesworld",
        // Static data file – compiled via include from another TU
        "ScummVMEngine/engines/supernova/screenstatic.cpp",
        // Macro-templated sprite-draw body – #include-d 12x by sprite.cpp with
        // different macros predefined each time, not a standalone TU
        "ScummVMEngine/engines/mads/core/sprite_0.cpp",
        // Orphaned duplicate of dont_frag_the_palette()/sprite_free()/etc.,
        // which sprite.cpp already defines itself; not #include-d or
        // referenced anywhere, and collides as a standalone TU
        "ScummVMEngine/engines/mads/core/sprite_k.cpp",
        // Buggy plugin stub – missing includes and wrong function names
        "ScummVMEngine/engines/ags/plugins/core/screen.cpp",
        // SDL3 backend – we use SDL2
        "ScummVMEngine/backends/events/sdl/sdl3-events.cpp",
        // SDL1 backend – we use SDL2
        "ScummVMEngine/backends/events/sdl/sdl1-events.cpp",
        "ScummVMEngine/backends/events/ds",
        "ScummVMEngine/backends/events/atari",
        "ScummVMEngine/backends/events/default/default-events.cpp",
        // SDL3 ImGui backend – we use SDL2
        "ScummVMEngine/backends/imgui/backends/imgui_impl_sdlrenderer3.cpp",
        "ScummVMEngine/backends/imgui/backends/imgui_impl_sdl3.cpp",
        // SDL2 ImGui backends are macOS-only in this package setup (iOS/tvOS builds use WITHOUT_SDL)
        "ScummVMEngine/backends/imgui/backends/imgui_impl_sdl2.cpp",
        "ScummVMEngine/backends/imgui/backends/imgui_impl_sdlrenderer2.cpp",
        "ScummVMEngine/base/main.cpp",
        "ScummVMEngine/engines/ags/engine/main/main.cpp",
        "ScummVMEngine/engines/bladerunner/script/ai/_template.cpp",
        "ScummVMEngine/engines/bagel",
        "ScummVMEngine/engines/bagel/hodjnpodj/archeroids/main.cpp",
        "ScummVMEngine/engines/bagel/hodjnpodj/barbershop/main.cpp",
        "ScummVMEngine/engines/bagel/hodjnpodj/crypt/main.cpp",
        "ScummVMEngine/engines/bagel/hodjnpodj/metagame",
        "ScummVMEngine/engines/bagel/hodjnpodj/novacancy/main.cpp",
        "ScummVMEngine/engines/bagel/hodjnpodj/pdq/main.cpp",
        "ScummVMEngine/engines/bagel/hodjnpodj/pdq/convert.cpp",
        "ScummVMEngineOverrides/backends/platform/ios7/ios7_video.mm",
        "ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_video.mm",
        "ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_main.cpp",
        "ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_events.cpp",
        "ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_sound.cpp",
        "ScummVMEngineOverrides/engines/got/game/got_game_main_override.cpp",
        "ScummVMEngineOverrides/engines/watchmaker/watchmaker_main_override.cpp",
        "ScummVMEngine/engines/chewy/main.cpp",
        "ScummVMEngine/engines/mads/dragonsphere/main.cpp",
        "ScummVMEngine/engines/mads/nebular/main.cpp",
        "ScummVMEngine/engines/mads/phantom/main.cpp",
        "ScummVMEngine/engines/mads/forest/main.cpp",
        "ScummVMEngine/engines/glk/alan2/main.cpp",
        "ScummVMEngine/engines/glk/alan3/main.cpp",
        "ScummVMEngine/engines/got/game/main.cpp",
        "ScummVMEngine/engines/petka/interfaces/main.cpp",
        "ScummVMEngine/engines/scumm/he/net/net_lobby.cpp",
        "ScummVMEngine/engines/ultima/ultima1/widgets/merchant_armor.cpp",
        "ScummVMEngine/engines/ultima/ultima1/actions/cast.cpp",
        "ScummVMEngine/engines/saga2/main.cpp",
        "ScummVMEngine/engines/watchmaker/main.cpp",
        "ScummVMEngine/engines/dgds/sound/drivers/fmtowns.cpp",
        "ScummVMEngine/engines/director/debugger",
        "ScummVMEngine/engines/qdengine/debugger/debugtools.cpp",
      ],
      resources: [
        // Core runtime payload expected by ScummVM. In binary mode the release
        // pipeline copies the same files into the framework's own Resources
        // directory - see scripts/build-engine-slice.sh, keep the two in sync.
        .copy("ScummVMEngine/dists/engine-data"),
        .copy("ScummVMEngine/dists/networking/wwwroot.zip"),
        .copy("ScummVMEngine/dists/soundfonts/Roland_SC-55.sf2"),
        .copy("ScummVMEngine/dists/soundfonts/COPYRIGHT.Roland_SC-55"),
        .copy("ScummVMEngine/dists/pred.dic"),

        // Theme payload (copy only runtime artifacts, not full source theme tree)
        .copy("ScummVMEngine/gui/themes/gui-icons.dat"),
        .copy("ScummVMEngine/gui/themes/residualvm.zip"),
        .copy("ScummVMEngine/gui/themes/scummclassic.zip"),
        .copy("ScummVMEngine/gui/themes/scummmodern.zip"),
        .copy("ScummVMEngine/gui/themes/scummremastered.zip"),
        .copy("ScummVMEngine/gui/themes/shaders.dat"),
        .copy("ScummVMEngine/gui/themes/translations.dat"),
      ],
      publicHeadersPath: "ScummVMEngine",
      cSettings: [
        // ScummVM sources are configured for RELEASE_BUILD in this package.
        // SwiftPM debug builds inject DEBUG=1 by default, which enables
        // debug-only code paths that rely on symbols not present here.
        .unsafeFlags(["-UDEBUG"])
      ],
      cxxSettings: [
        .headerSearchPath("."),
        .headerSearchPath("ScummVMEngineOverrides"),
        .headerSearchPath("ScummVMEngine"),
        .headerSearchPath("ScummVMEngine/engines"),
        .unsafeFlags(["-UDEBUG"]),
        .unsafeFlags(["-fno-objc-arc"], .when(platforms: [.macOS])),
        .unsafeFlags(["-UYES", "-UNO"], .when(platforms: [.macOS])),
        .unsafeFlags(["-include", "ScummVMNoObjCMacros.h"], .when(platforms: [.macOS])),
        .unsafeFlags(["-include", "ScummVMObjCYesNoConsts.h"], .when(platforms: [.macOS])),
        .unsafeFlags(["-include", "ScummVMAGSAlconfigBridge.h"]),
        .define("ENABLE_EVENTRECORDER", .when(platforms: [.macOS])),
        .define("ENABLE_WME3D"),
        .define("USE_ZLIB"),
        .define("USE_MAD"),
        .define("USE_FRIBIDI"),
        .define("USE_OGG"),
        .define("USE_VORBIS"),
        .define("USE_FLAC"),
        .define("USE_PNG"),
        .define("USE_GIF"),
        .define("USE_FAAD"),
        .define("USE_MIKMOD"),
        .define("USE_MPEG2"),
        .define("USE_THEORADEC"),
        .define("USE_FREETYPE2"),
        .define("USE_JPEG"),
        .define("USE_FLUIDSYNTH"),
        .define("USE_LIBCURL"),
        .define("USE_SDL_NET"),
        .define("USE_BINK"),
        .define("USE_SCALERS"),
        .define("USE_HQ_SCALERS"),
        .define("USE_EDGE_SCALERS"),
        .define("USE_ASPECT"),
        .define("USE_RGB_COLOR"),
        .define("USE_HIGHRES"),
        .define("USE_MT32EMU"),
        .define("USE_OPENGL"),
        .define("USE_OPENGL_GAME"),
        .define("USE_OPENGL_SHADERS"),
        .define("USE_CLOUD"),
        .define("USE_ENET"),
        .define("USE_TRANSLATION"),
        .define("USE_SYSDIALOGS"),
        .define("USE_DETECTLANG"),
        .define("BUILTIN_RESOURCES", .when(platforms: [.macOS])),
        .define("USE_DETECTION_FEATURES_STATIC"),
        .define("USE_FMTOWNS_PC98_AUDIO"),
        .define("USE_HNM"),
        .define("USE_INDEO3"),
        .define("USE_INDEO45"),
        .define("USE_LUA"),
        .define("USE_MIDI"),
        .define("USE_SID_AUDIO"),
        .define("USE_TINYGL"),
        .define("USE_UNIVERSALTRACKER"),
        .define("USE_VGMTRANS_AUDIO"),
        .define("ENABLE_SCUMM"),
        .define("ENABLE_SCUMM_7_8"),
        .define("ENABLE_HE"),
        .define("ENABLE_ACCESS"),
        .define("ENABLE_ADL"),
        .define("ENABLE_AGI"),
        .define("ENABLE_AGOS"),
        .define("ENABLE_AGOS2"),
        .define("ENABLE_AGS"),
        .define("ENABLE_ASYLUM"),
        .define("ENABLE_BBVS"),
        .define("ENABLE_BLADERUNNER"),
        .define("ENABLE_BURIED"),
        .define("ENABLE_CGE"),
        .define("ENABLE_CGE2"),
        .define("ENABLE_CHEWY"),
        .define("ENABLE_CINE"),
        .define("ENABLE_COMPOSER"),
        .define("ENABLE_CRAB"),
        .define("ENABLE_CRUISE"),
        .define("ENABLE_CRYOMNI3D"),
        .define("ENABLE_VERSAILLES"),
        .define("ENABLE_DARKSEED"),
        .define("ENABLE_DGDS"),
        .define("ENABLE_DIRECTOR"),
        .define("ENABLE_DRACI"),
        .define("ENABLE_DRAGONS"),
        .define("ENABLE_DRASCULA"),
        .define("ENABLE_DREAMWEB"),
        .define("ENABLE_EFH"),
        .define("ENABLE_FREESCAPE"),
        .define("ENABLE_GLK"),
        .define("ENABLE_GNAP"),
        .define("ENABLE_GOB"),
        .define("ENABLE_GRIFFON"),
        .define("ENABLE_GRIM"),
        .define("ENABLE_GROOVIE"),
        .define("ENABLE_GROOVIE2"),
        .define("ENABLE_HADESCH"),
        .define("ENABLE_HDB"),
        .define("ENABLE_HOPKINS"),
        .define("ENABLE_HUGO"),
        .define("ENABLE_HYPNO"),
        .define("ENABLE_ILLUSIONS"),
        .define("ENABLE_KINGDOM"),
        .define("ENABLE_KYRA"),
        .define("ENABLE_LOL"),
        .define("ENABLE_EOB"),
        .define("ENABLE_LAB"),
        .define("ENABLE_LURE"),
        .define("ENABLE_M4"),
        .define("ENABLE_MADE"),
        .define("ENABLE_MADS"),
        .define("ENABLE_MM"),
        .define("ENABLE_MM1"),
        .define("ENABLE_XEEN"),
        .define("ENABLE_MOHAWK"),
        .define("ENABLE_CSTIME"),
        .define("ENABLE_RIVEN"),
        .define("ENABLE_MYST"),
        .define("ENABLE_MYSTME"),
        .define("ENABLE_MORTEVIELLE"),
        .define("ENABLE_MTROPOLIS"),
        .define("ENABLE_MYST3"),
        .define("ENABLE_NANCY"),
        .define("ENABLE_NEVERHOOD"),
        .define("ENABLE_NGI"),
        .define("ENABLE_PARALLACTION"),
        .define("ENABLE_PEGASUS"),
        .define("ENABLE_PETKA"),
        .define("ENABLE_PINK"),
        .define("ENABLE_PLUMBERS"),
        .define("ENABLE_PRINCE"),
        .define("ENABLE_PRIVATE"),
        .define("ENABLE_QDENGINE"),
        .define("ENABLE_QUEEN"),
        .define("ENABLE_SAGA"),
        .define("ENABLE_IHNM"),
        .define("ENABLE_SAGA2"),
        .define("ENABLE_SCI"),
        .define("ENABLE_SCI32"),
        .define("ENABLE_SHERLOCK"),
        .define("ENABLE_SKY"),
        .define("ENABLE_STARK"),
        .define("ENABLE_SUPERNOVA"),
        .define("ENABLE_SWORD1"),
        .define("ENABLE_SWORD2"),
        .define("ENABLE_SWORD25"),
        .define("ENABLE_TEENAGENT"),
        .define("ENABLE_TETRAEDGE"),
        .define("ENABLE_TINSEL"),
        .define("ENABLE_TITANIC"),
        .define("ENABLE_TOLTECS"),
        .define("ENABLE_TONY"),
        .define("ENABLE_TOON"),
        .define("ENABLE_TOUCHE"),
        .define("ENABLE_TRECISION"),
        .define("ENABLE_TSAGE"),
        .define("ENABLE_RINGWORLD"),
        .define("ENABLE_BLUEFORCE"),
        .define("ENABLE_RINGWORLD2"),
        .define("ENABLE_TUCKER"),
        .define("ENABLE_TWINE"),
        .define("ENABLE_TWP"),
        .define("ENABLE_ULTIMA"),
        .define("ENABLE_ULTIMA4"),
        .define("ENABLE_ULTIMA6"),
        .define("ENABLE_ULTIMA8"),
        .define("ENABLE_VCRUISE"),
        .define("ENABLE_VOYEUR"),
        .define("ENABLE_WINTERMUTE"),
        .define("ENABLE_FOXTAIL"),
        .define("ENABLE_HEROCRAFT"),
        .define("ENABLE_ZVISION"),
        .define("DETECTION_STATIC"),
        .define("POSIX"),
        .define("USE_SDL2", .when(platforms: [.macOS])),
        .define("USE_GLAD"),
        .define("CONFIG_H"),
        .define("UNIX"),
        .define("HAS_FSEEKO_OFFT_64"),
        .define("SCUMMVM"),
        .define("RELEASE_BUILD"),
        .define("IPHONE", .when(platforms: [.iOS, .tvOS])),
        .define("IPHONE_IOS7", .when(platforms: [.iOS, .tvOS])),
        .define("IPHONE_TVOS", .when(platforms: [.tvOS])),
        .define("WITHOUT_SDL", .when(platforms: [.iOS, .tvOS])),
        .define("SCUMMVM_NEON", .when(platforms: [.iOS, .tvOS])),
        .define("SDL_BACKEND", .when(platforms: [.macOS])),
        .define("MACOSX", .when(platforms: [.macOS])),
      ],
      linkerSettings: [
        .linkedLibrary("c++"),
        .linkedLibrary("z"),
        .linkedLibrary("iconv"),
        .linkedFramework("AudioToolbox"),
        .linkedFramework("CoreAudio"),
        .linkedFramework("CoreFoundation"),
        .linkedFramework("CoreGraphics"),
        .linkedFramework("CoreMIDI"),
        .linkedFramework("Foundation"),
        .linkedFramework("GameController"),
        .linkedFramework("QuartzCore"),
        .linkedFramework("Security"),
        .linkedFramework("SystemConfiguration"),
        .linkedFramework("OpenGLES", .when(platforms: [.iOS, .tvOS])),
        .linkedFramework("UIKit", .when(platforms: [.iOS, .tvOS])),
        .linkedLibrary("lber", .when(platforms: [.macOS])),
        .linkedLibrary("ldap", .when(platforms: [.macOS])),
        .linkedFramework("AppKit", .when(platforms: [.macOS])),
        .linkedFramework("OpenGL", .when(platforms: [.macOS])),
        .linkedFramework("Metal", .when(platforms: [.macOS])),
        .linkedFramework("CoreHaptics", .when(platforms: [.macOS])),
        .linkedFramework("ForceFeedback", .when(platforms: [.macOS])),
        .linkedFramework("AudioUnit", .when(platforms: [.macOS])),
        .linkedFramework("Cocoa", .when(platforms: [.macOS])),
        .linkedFramework("Carbon", .when(platforms: [.macOS])),
        .linkedFramework("ApplicationServices", .when(platforms: [.macOS])),
        .linkedFramework("IOKit", .when(platforms: [.macOS])),
      ]
    ),
    .target(
      name: "ScummVMmacOS",
      dependencies: [
        "ScummVMEngine"
      ],
      path: "swift/Sources",
      exclude: [
        // Prevent implicit resource discovery from upstream distribution payload.
        "ScummVMEngine/dists"
      ],
      sources: [
        "ScummVMmacOS/ScummVMEngine.mm",
        "ScummVMmacOS/ScummVMAppContext.mm",
        "ScummVMEngine/backends/graphics/sdl/sdl-graphics.cpp",
        "ScummVMEngine/backends/graphics/openglsdl/openglsdl-graphics.cpp",
        "ScummVMEngine/backends/graphics/surfacesdl/surfacesdl-graphics.cpp",
        "ScummVMEngine/backends/imgui/backends/imgui_impl_sdl2.cpp",
        "ScummVMEngine/backends/imgui/backends/imgui_impl_sdlrenderer2.cpp",
        "ScummVMEngine/backends/platform/sdl/sdl-window.cpp",
        "ScummVMEngine/backends/platform/sdl/sdl.cpp",
        "ScummVMEngine/backends/platform/sdl/posix/posix.cpp",
        "ScummVMEngine/backends/platform/sdl/macosx/appmenu_osx.mm",
        "ScummVMEngine/backends/platform/sdl/macosx/macosx-touchbar.mm",
        "ScummVMEngine/backends/platform/sdl/macosx/macosx-window.mm",
        "ScummVMEngine/backends/platform/sdl/macosx/macosx.cpp",
        "ScummVMEngine/backends/platform/sdl/macosx/macosx_osys_misc.mm",
        "ScummVMEngine/backends/platform/sdl/macosx/macosx_wrapper.mm",
      ],
      resources: [
        // Only copy the Sparkle DSA key; copying the full macOS app template
        // embeds nested Info.plist files that fail App Store/TestFlight validation.
        .copy("ScummVMEngine/dists/macosx/dsa_pub.pem")
      ],
      publicHeadersPath: "ScummVMmacOS/include",
      cSettings: [
        .headerSearchPath("ScummVMmacOS"),
        .headerSearchPath("ScummVMEngineOverrides"),
        .unsafeFlags(["-fno-objc-arc"]),
        .unsafeFlags(["-include", "ScummVMObjCYesNoConsts.h"]),
      ],
      cxxSettings: [
        .headerSearchPath("ScummVMmacOS"),
        .headerSearchPath("ScummVMEngineOverrides"),
        .headerSearchPath("ScummVMEngine"),
        .headerSearchPath("ScummVMEngine/engines"),
        .headerSearchPath("ScummVMEngine/backends/platform/sdl/macosx"),
        .unsafeFlags(["-include", "ScummVMObjCYesNoConsts.h"]),
        .define("ENABLE_WME3D"),
        .define("USE_ZLIB"),
        .define("USE_MAD"),
        .define("USE_FRIBIDI"),
        .define("USE_OGG"),
        .define("USE_VORBIS"),
        .define("USE_FLAC"),
        .define("USE_PNG"),
        .define("USE_GIF"),
        .define("USE_FAAD"),
        .define("USE_MIKMOD"),
        .define("USE_MPEG2"),
        .define("USE_THEORADEC"),
        .define("USE_FREETYPE2"),
        .define("USE_JPEG"),
        .define("USE_FLUIDSYNTH"),
        .define("USE_LIBCURL"),
        .define("USE_SDL_NET"),
        .define("USE_BINK"),
        .define("USE_SCALERS"),
        .define("USE_HQ_SCALERS"),
        .define("USE_EDGE_SCALERS"),
        .define("USE_ASPECT"),
        .define("USE_RGB_COLOR"),
        .define("USE_HIGHRES"),
        .define("USE_MT32EMU"),
        .define("USE_OPENGL"),
        .define("USE_OPENGL_GAME"),
        .define("USE_OPENGL_SHADERS"),
        .define("USE_CLOUD"),
        .define("USE_ENET"),
        .define("USE_TRANSLATION"),
        .define("USE_SYSDIALOGS"),
        .define("USE_DETECTLANG"),
        .define("BUILTIN_RESOURCES"),
        .define("USE_DETECTION_FEATURES_STATIC"),
        .define("USE_FMTOWNS_PC98_AUDIO"),
        .define("USE_HNM"),
        .define("USE_INDEO3"),
        .define("USE_INDEO45"),
        .define("USE_LUA"),
        .define("USE_MIDI"),
        .define("USE_SID_AUDIO"),
        .define("USE_TINYGL"),
        .define("USE_UNIVERSALTRACKER"),
        .define("USE_VGMTRANS_AUDIO"),
        .define("ENABLE_SCUMM"),
        .define("ENABLE_SCUMM_7_8"),
        .define("ENABLE_HE"),
        .define("ENABLE_ACCESS"),
        .define("ENABLE_ADL"),
        .define("ENABLE_AGI"),
        .define("ENABLE_AGOS"),
        .define("ENABLE_AGOS2"),
        .define("ENABLE_AGS"),
        .define("ENABLE_ASYLUM"),
        .define("ENABLE_BBVS"),
        .define("ENABLE_BLADERUNNER"),
        .define("ENABLE_BURIED"),
        .define("ENABLE_CGE"),
        .define("ENABLE_CGE2"),
        .define("ENABLE_CHEWY"),
        .define("ENABLE_CINE"),
        .define("ENABLE_COMPOSER"),
        .define("ENABLE_CRAB"),
        .define("ENABLE_CRUISE"),
        .define("ENABLE_CRYOMNI3D"),
        .define("ENABLE_VERSAILLES"),
        .define("ENABLE_DARKSEED"),
        .define("ENABLE_DGDS"),
        .define("ENABLE_DIRECTOR"),
        .define("ENABLE_DRACI"),
        .define("ENABLE_DRAGONS"),
        .define("ENABLE_DRASCULA"),
        .define("ENABLE_DREAMWEB"),
        .define("ENABLE_EFH"),
        .define("ENABLE_FREESCAPE"),
        .define("ENABLE_GLK"),
        .define("ENABLE_GNAP"),
        .define("ENABLE_GOB"),
        .define("ENABLE_GRIFFON"),
        .define("ENABLE_GRIM"),
        .define("ENABLE_GROOVIE"),
        .define("ENABLE_GROOVIE2"),
        .define("ENABLE_HADESCH"),
        .define("ENABLE_HDB"),
        .define("ENABLE_HOPKINS"),
        .define("ENABLE_HUGO"),
        .define("ENABLE_HYPNO"),
        .define("ENABLE_ILLUSIONS"),
        .define("ENABLE_KINGDOM"),
        .define("ENABLE_KYRA"),
        .define("ENABLE_LOL"),
        .define("ENABLE_EOB"),
        .define("ENABLE_LAB"),
        .define("ENABLE_LURE"),
        .define("ENABLE_M4"),
        .define("ENABLE_MADE"),
        .define("ENABLE_MADS"),
        .define("ENABLE_MM"),
        .define("ENABLE_MM1"),
        .define("ENABLE_XEEN"),
        .define("ENABLE_MOHAWK"),
        .define("ENABLE_RIVEN"),
        .define("ENABLE_MYST"),
        .define("ENABLE_MYSTME"),
        .define("ENABLE_MORTEVIELLE"),
        .define("ENABLE_MTROPOLIS"),
        .define("ENABLE_MYST3"),
        .define("ENABLE_NANCY"),
        .define("ENABLE_NEVERHOOD"),
        .define("ENABLE_NGI"),
        .define("ENABLE_PARALLACTION"),
        .define("ENABLE_PEGASUS"),
        .define("ENABLE_PETKA"),
        .define("ENABLE_PINK"),
        .define("ENABLE_PLUMBERS"),
        .define("ENABLE_PRINCE"),
        .define("ENABLE_PRIVATE"),
        .define("ENABLE_QDENGINE"),
        .define("ENABLE_QUEEN"),
        .define("ENABLE_SAGA"),
        .define("ENABLE_IHNM"),
        .define("ENABLE_SAGA2"),
        .define("ENABLE_SCI"),
        .define("ENABLE_SCI32"),
        .define("ENABLE_SHERLOCK"),
        .define("ENABLE_SKY"),
        .define("ENABLE_STARK"),
        .define("ENABLE_SUPERNOVA"),
        .define("ENABLE_SWORD1"),
        .define("ENABLE_SWORD2"),
        .define("ENABLE_SWORD25"),
        .define("ENABLE_TEENAGENT"),
        .define("ENABLE_TETRAEDGE"),
        .define("ENABLE_TINSEL"),
        .define("ENABLE_TITANIC"),
        .define("ENABLE_TOLTECS"),
        .define("ENABLE_TONY"),
        .define("ENABLE_TOON"),
        .define("ENABLE_TOUCHE"),
        .define("ENABLE_TRECISION"),
        .define("ENABLE_TSAGE"),
        .define("ENABLE_RINGWORLD"),
        .define("ENABLE_BLUEFORCE"),
        .define("ENABLE_RINGWORLD2"),
        .define("ENABLE_TUCKER"),
        .define("ENABLE_TWINE"),
        .define("ENABLE_TWP"),
        .define("ENABLE_ULTIMA"),
        .define("ENABLE_ULTIMA4"),
        .define("ENABLE_ULTIMA6"),
        .define("ENABLE_ULTIMA8"),
        .define("ENABLE_VCRUISE"),
        .define("ENABLE_VOYEUR"),
        .define("ENABLE_WINTERMUTE"),
        .define("ENABLE_FOXTAIL"),
        .define("ENABLE_HEROCRAFT"),
        .define("ENABLE_ZVISION"),
        .define("POSIX"),
        .define("DETECTION_STATIC"),
        .define("USE_GLAD"),
        .define("CONFIG_H"),
        .define("UNIX"),
        .define("HAS_FSEEKO_OFFT_64"),
        .define("SCUMMVM"),
        .define("RELEASE_BUILD"),
        .define("SDL_BACKEND", .when(platforms: [.macOS])),
        .define("MACOSX", .when(platforms: [.macOS])),
        .unsafeFlags(["-fno-objc-arc"]),
      ]
    ),
    .target(
      name: "ScummVMiOS",
      dependencies: [
        "ScummVMEngine"
      ],
      path: "swift/Sources",
      exclude: [
        // Prevent implicit resource discovery from upstream distribution payload.
        "ScummVMEngine/dists"
      ],
      sources: [
        "ScummVMiOS/ScummVMEngine.mm",
        "ScummVMiOS/ScummVMAppContext.mm",
        "ScummVMiOS/ScummVMAppDelegate.mm",
        "ScummVMiOS/ScummVMIOSBridge.cpp",
        "ScummVMEngine/backends/graphics/ios/ios-graphics.cpp",
        "ScummVMEngine/backends/graphics/ios/renderbuffer.cpp",
        "ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_main.cpp",
        "ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_events.cpp",
        "ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_sound.cpp",
        "ScummVMEngineOverrides/backends/platform/ios7/ios7_osys_video.mm",
        "ScummVMEngine/backends/platform/ios7/ios7_osys_misc.mm",
        "ScummVMEngine/backends/platform/ios7/ios7_misc.mm",
        "ScummVMEngine/backends/platform/ios7/ios7_options.mm",
        "ScummVMEngineOverrides/backends/platform/ios7/ios7_video.mm",
        "ScummVMEngine/backends/platform/ios7/ios7_keyboard.mm",
        "ScummVMEngine/backends/platform/ios7/ios7_scummvm_view_controller.mm",
        "ScummVMEngine/backends/platform/ios7/ios7_game_controller.mm",
        "ScummVMEngine/backends/platform/ios7/ios7_touch_controller.mm",
        "ScummVMEngine/backends/platform/ios7/ios7_mouse_controller.mm",
        "ScummVMEngine/backends/platform/ios7/ios7_gamepad_controller.mm",
      ],
      resources: [
        // Platform-specific metadata/assets
        .process("ScummVMEngine/dists/ios7/Images.xcassets"),
        .copy("ScummVMEngine/dists/ios7/PrivacyInfo.xcprivacy"),
      ],
      publicHeadersPath: "ScummVMiOS/include",
      cSettings: [
        .headerSearchPath("ScummVMiOS/include"),
        .headerSearchPath("ScummVMiOS"),
        .headerSearchPath("ScummVMEngineOverrides"),
        .unsafeFlags(["-fno-objc-arc"]),
        .unsafeFlags(["-include", "ScummVMObjCYesNoConsts.h"]),
      ],
      cxxSettings: [
        .headerSearchPath("ScummVMiOS/include"),
        .headerSearchPath("ScummVMiOS"),
        .headerSearchPath("ScummVMEngineOverrides"),
        .headerSearchPath("ScummVMEngine"),
        .headerSearchPath("ScummVMEngine/engines"),
        .headerSearchPath("ScummVMEngine/backends/platform/ios7"),
        .unsafeFlags(["-include", "ScummVMObjCYesNoConsts.h"]),
        .define("ENABLE_WME3D"),
        .define("USE_ZLIB"),
        .define("USE_MAD"),
        .define("USE_FRIBIDI"),
        .define("USE_OGG"),
        .define("USE_VORBIS"),
        .define("USE_FLAC"),
        .define("USE_PNG"),
        .define("USE_GIF"),
        .define("USE_FAAD"),
        .define("USE_MIKMOD"),
        .define("USE_MPEG2"),
        .define("USE_THEORADEC"),
        .define("USE_FREETYPE2"),
        .define("USE_JPEG"),
        .define("USE_FLUIDSYNTH"),
        .define("USE_LIBCURL"),
        .define("USE_SDL_NET"),
        .define("USE_BINK"),
        .define("USE_SCALERS"),
        .define("USE_HQ_SCALERS"),
        .define("USE_EDGE_SCALERS"),
        .define("USE_ASPECT"),
        .define("USE_RGB_COLOR"),
        .define("USE_HIGHRES"),
        .define("USE_MT32EMU"),
        .define("USE_OPENGL"),
        .define("USE_OPENGL_GAME"),
        .define("USE_OPENGL_SHADERS"),
        .define("USE_CLOUD"),
        .define("USE_ENET"),
        .define("USE_TRANSLATION"),
        .define("USE_SYSDIALOGS"),
        .define("USE_DETECTLANG"),
        .define("USE_DETECTION_FEATURES_STATIC"),
        .define("USE_FMTOWNS_PC98_AUDIO"),
        .define("USE_HNM"),
        .define("USE_INDEO3"),
        .define("USE_INDEO45"),
        .define("USE_LUA"),
        .define("USE_MIDI"),
        .define("USE_SID_AUDIO"),
        .define("USE_TINYGL"),
        .define("USE_UNIVERSALTRACKER"),
        .define("USE_VGMTRANS_AUDIO"),
        .define("ENABLE_SCUMM"),
        .define("ENABLE_SCUMM_7_8"),
        .define("ENABLE_HE"),
        .define("ENABLE_ACCESS"),
        .define("ENABLE_ADL"),
        .define("ENABLE_AGI"),
        .define("ENABLE_AGOS"),
        .define("ENABLE_AGOS2"),
        .define("ENABLE_AGS"),
        .define("ENABLE_ASYLUM"),
        .define("ENABLE_BBVS"),
        .define("ENABLE_BLADERUNNER"),
        .define("ENABLE_BURIED"),
        .define("ENABLE_CGE"),
        .define("ENABLE_CGE2"),
        .define("ENABLE_CHEWY"),
        .define("ENABLE_CINE"),
        .define("ENABLE_COMPOSER"),
        .define("ENABLE_CRAB"),
        .define("ENABLE_CRUISE"),
        .define("ENABLE_CRYOMNI3D"),
        .define("ENABLE_VERSAILLES"),
        .define("ENABLE_DARKSEED"),
        .define("ENABLE_DGDS"),
        .define("ENABLE_DIRECTOR"),
        .define("ENABLE_DRACI"),
        .define("ENABLE_DRAGONS"),
        .define("ENABLE_DRASCULA"),
        .define("ENABLE_DREAMWEB"),
        .define("ENABLE_EFH"),
        .define("ENABLE_FREESCAPE"),
        .define("ENABLE_GLK"),
        .define("ENABLE_GNAP"),
        .define("ENABLE_GOB"),
        .define("ENABLE_GRIFFON"),
        .define("ENABLE_GRIM"),
        .define("ENABLE_GROOVIE"),
        .define("ENABLE_GROOVIE2"),
        .define("ENABLE_HADESCH"),
        .define("ENABLE_HDB"),
        .define("ENABLE_HOPKINS"),
        .define("ENABLE_HUGO"),
        .define("ENABLE_HYPNO"),
        .define("ENABLE_ILLUSIONS"),
        .define("ENABLE_KINGDOM"),
        .define("ENABLE_KYRA"),
        .define("ENABLE_LOL"),
        .define("ENABLE_EOB"),
        .define("ENABLE_LAB"),
        .define("ENABLE_LURE"),
        .define("ENABLE_M4"),
        .define("ENABLE_MADE"),
        .define("ENABLE_MADS"),
        .define("ENABLE_MM"),
        .define("ENABLE_MM1"),
        .define("ENABLE_XEEN"),
        .define("ENABLE_MOHAWK"),
        .define("ENABLE_RIVEN"),
        .define("ENABLE_MYST"),
        .define("ENABLE_MYSTME"),
        .define("ENABLE_MORTEVIELLE"),
        .define("ENABLE_MTROPOLIS"),
        .define("ENABLE_MYST3"),
        .define("ENABLE_NANCY"),
        .define("ENABLE_NEVERHOOD"),
        .define("ENABLE_NGI"),
        .define("ENABLE_PARALLACTION"),
        .define("ENABLE_PEGASUS"),
        .define("ENABLE_PETKA"),
        .define("ENABLE_PINK"),
        .define("ENABLE_PLUMBERS"),
        .define("ENABLE_PRINCE"),
        .define("ENABLE_PRIVATE"),
        .define("ENABLE_QDENGINE"),
        .define("ENABLE_QUEEN"),
        .define("ENABLE_SAGA"),
        .define("ENABLE_IHNM"),
        .define("ENABLE_SAGA2"),
        .define("ENABLE_SCI"),
        .define("ENABLE_SCI32"),
        .define("ENABLE_SHERLOCK"),
        .define("ENABLE_SKY"),
        .define("ENABLE_STARK"),
        .define("ENABLE_SUPERNOVA"),
        .define("ENABLE_SWORD1"),
        .define("ENABLE_SWORD2"),
        .define("ENABLE_SWORD25"),
        .define("ENABLE_TEENAGENT"),
        .define("ENABLE_TETRAEDGE"),
        .define("ENABLE_TINSEL"),
        .define("ENABLE_TITANIC"),
        .define("ENABLE_TOLTECS"),
        .define("ENABLE_TONY"),
        .define("ENABLE_TOON"),
        .define("ENABLE_TOUCHE"),
        .define("ENABLE_TRECISION"),
        .define("ENABLE_TSAGE"),
        .define("ENABLE_RINGWORLD"),
        .define("ENABLE_BLUEFORCE"),
        .define("ENABLE_RINGWORLD2"),
        .define("ENABLE_TUCKER"),
        .define("ENABLE_TWINE"),
        .define("ENABLE_TWP"),
        .define("ENABLE_ULTIMA"),
        .define("ENABLE_ULTIMA4"),
        .define("ENABLE_ULTIMA6"),
        .define("ENABLE_ULTIMA8"),
        .define("ENABLE_VCRUISE"),
        .define("ENABLE_VOYEUR"),
        .define("ENABLE_WINTERMUTE"),
        .define("ENABLE_FOXTAIL"),
        .define("ENABLE_HEROCRAFT"),
        .define("ENABLE_ZVISION"),
        .define("POSIX"),
        .define("DETECTION_STATIC"),
        .define("USE_GLAD"),
        .define("CONFIG_H"),
        .define("UNIX"),
        .define("HAS_FSEEKO_OFFT_64"),
        .define("SCUMMVM"),
        .define("RELEASE_BUILD"),
        .define("IPHONE", .when(platforms: [.iOS, .tvOS])),
        .define("IPHONE_IOS7", .when(platforms: [.iOS, .tvOS])),
        .define("IPHONE_TVOS", .when(platforms: [.tvOS])),
        .define("WITHOUT_SDL", .when(platforms: [.iOS, .tvOS])),
        .define("SCUMMVM_NEON", .when(platforms: [.iOS, .tvOS])),
        .unsafeFlags(["-fno-objc-arc"]),
      ]
    ),
    .target(
      name: "ScummVMtvOS",
      dependencies: [
        "ScummVMiOS"
      ],
      path: "swift/Sources/ScummVMtvOS",
      resources: tvOSResources
    ),

    scummVMBinaryTarget(
      name: "a52",
      checksum: "d389d7055deb36bf779853d51f6dbd653d91dbcb7fee382786b969de8b2081db"
    ),
    scummVMBinaryTarget(
      name: "bz2",
      checksum: "2b16e6713db951acb6e06da11145469115a6f0650237d1787a8f3e7f0bdc12ff"
    ),
    scummVMBinaryTarget(
      name: "curl",
      checksum: "6e6977bad5c44a97712655c76fb81eb56c02aab3ca8c29c728bf3dd0269df8dd"
    ),
    scummVMBinaryTarget(
      name: "faad",
      checksum: "ec84329b992724c799ad8aee1071c5b8f6382d8c540e967785f96edf9bb87672"
    ),
    scummVMBinaryTarget(
      name: "ffi",
      checksum: "0ada0e580efc9e5c7ca0c17a04499bd25654709dfc91731fd835ec26b04815ad"
    ),
    scummVMBinaryTarget(
      name: "FLAC",
      checksum: "aa3c469bfb104f6bb8717d6033cda99c27f16d16031e19e1e2491678d8bb94b6"
    ),
    scummVMBinaryTarget(
      name: "fluidsynth",
      checksum: "864ae3f5eaef39c43ceb8b9ad7cfa242010ad20d7756f3d2340b66c9b0e18fa4"
    ),
    scummVMBinaryTarget(
      name: "freetype",
      checksum: "71c6c65222daeaf345bbb316fe70423d0db369f0820cdb81dabe68287463c78e"
    ),
    scummVMBinaryTarget(
      name: "fribidi",
      checksum: "15bf1673a3e706aa46f5a71eae585be3a20cf2402e2d03340506d05df47c18e0"
    ),
    scummVMBinaryTarget(
      name: "gif",
      checksum: "a0463ef3ba12c6fbafe223d2ae063d43dd56c94dbbb8e36f041c6c5072085557"
    ),
    scummVMBinaryTarget(
      name: "glib-2.0",
      checksum: "41a33cdc196bffd972752cd0c16b06b5daf60fe4aa1b123f2e0d08489ea22040"
    ),
    scummVMBinaryTarget(
      name: "intl",
      checksum: "bc9c91956f78d0830b653efc98a38f96adfcc2a049b6bb59f720e401efe82bf1"
    ),
    scummVMBinaryTarget(
      name: "jpeg",
      checksum: "6a83eef6a7c885e05fedf9870538396a743d7dd9ded6b637dddc40d09c82d749"
    ),
    scummVMBinaryTarget(
      name: "mad",
      checksum: "bf040e3ff3d11a612d70d7aa37275d0b1c1a86549ed9178ec46b693ac7c92048"
    ),
    scummVMBinaryTarget(
      name: "mikmod",
      checksum: "363f6cb9a6b269636245b852f2f15242bef3255b69b9bea9ed2a1628ba628bd7"
    ),
    scummVMBinaryTarget(
      name: "mpeg2",
      checksum: "4b883dba8c5ef81669a5ee5b8bcfc773d2c2c1fdd17a750d0bbcabcdcdbb7050"
    ),
    scummVMBinaryTarget(
      name: "ogg",
      checksum: "d78d39567e53f94fdbee93d21065d07b96f35f099e6a5c17a5c1d5f58dfbb445"
    ),
    scummVMBinaryTarget(
      name: "png",
      checksum: "a27e1a1a7b9d67dc956f5ee8ab83b047b408b1e6b6e1f06f6f52883dfe62f634"
    ),
    scummVMBinaryTarget(
      name: "SDL2_net",
      checksum: "eb50388fa0aa5a23a1c6476d7bf124003382e344248d2ac6f0dbe4dc010b2c50"
    ),
    scummVMBinaryTarget(
      name: "SDL2",
      checksum: "2e2e591f2c1d7af4b465f49ccbe5ddd7f77c14ee1b803027b28a4dc992863f71"
    ),
    scummVMBinaryTarget(
      name: "theoradec",
      checksum: "eddf9491aa3042499821a3152e2f4f19f7adf544a4b48a02272b39a423ed674f"
    ),
    scummVMBinaryTarget(
      name: "vorbis",
      checksum: "b33a2c7d80f2ac71990ee7a2c79c3a986adb43d39f16520d6d3a4a9fcfad4a30"
    ),
    scummVMBinaryTarget(
      name: "vorbisfile",
      checksum: "96f5ef4d769390464a8b7a93328985d799bd26a5d583432778fecc5ba8557e67"
    ),
    scummVMBinaryTarget(
      name: "vpx",
      checksum: "8777c659010e27e158357dde6d418a00af9670df50a608e02b2264e9d61b8a3f"
    ),
  ]
  : [
    scummVMEngineBinaryTarget(
      name: "ScummVMiOS",
      checksum: engineChecksumiOS
    ),
    scummVMEngineBinaryTarget(
      name: "ScummVMtvOS",
      checksum: engineChecksumtvOS
    ),
    scummVMEngineBinaryTarget(
      name: "ScummVMmacOS",
      checksum: engineChecksummacOS
    ),
  ]

let package = Package(
  name: "swift-scummvm",
  platforms: [
    .iOS(.v17), .tvOS(.v17), .macOS(.v15),
  ],
  products: [
    .library(
      name: "ScummVM",
      targets: ["ScummVM"]
    ),
    .executable(
      name: "ScummVMApp",
      targets: ["ScummVMApp"]
    ),
    .library(
      name: "ScummVMiOS",
      targets: ["ScummVMiOS"]
    ),
    .library(
      name: "ScummVMmacOS",
      targets: ["ScummVMmacOS"]
    ),
    .library(
      name: "ScummVMtvOS",
      targets: ["ScummVMtvOS"]
    ),
  ],
  dependencies: [
    .package(url: "https://github.com/weichsel/ZIPFoundation.git", from: "0.9.20")
  ],
  targets: [
    .target(
      name: "ScummVM",
      dependencies: [
        .product(name: "ZIPFoundation", package: "ZIPFoundation"),
        .target(name: "ScummVMmacOS", condition: .when(platforms: [.macOS])),
        .target(name: "ScummVMiOS", condition: .when(platforms: [.iOS])),
        .target(name: "ScummVMtvOS", condition: .when(platforms: [.tvOS])),
      ],
      path: "swift/Sources/ScummVM"
    ),
    .executableTarget(
      name: "ScummVMApp",
      dependencies: [
        .target(name: "ScummVM", condition: .when(platforms: [.macOS]))
      ],
      path: "swift/Sources/ScummVMApp"
    ),
    .testTarget(
      name: "ScummVMTests",
      dependencies: [
        "ScummVM",
        // Only macOS runs `swift test` in CI (see ci.yml's build-binary job), and
        // only against the prebuilt engine - exercising the ObjC facade directly
        // requires this import on that platform.
        .target(name: "ScummVMmacOS", condition: .when(platforms: [.macOS])),
      ],
      path: "swift/Tests/ScummVMTests"
    ),
  ] + engineTargets,
  cLanguageStandard: .c11,
  cxxLanguageStandard: .cxx17
)

func scummVMBinaryTarget(
  name: String,
  checksum: String,
  baseURL: String = binaryBaseURL
) -> Target {
  let url = "\(baseURL)/\(name).xcframework.zip"
  return .binaryTarget(
    name: name,
    url: url,
    checksum: checksum)
}

func scummVMEngineBinaryTarget(name: String, checksum: String) -> Target {
  if let localEngineArtifactsPath {
    return .binaryTarget(
      name: name,
      path: "\(localEngineArtifactsPath)/\(name).xcframework"
    )
  }
  return scummVMBinaryTarget(
    name: name,
    checksum: checksum,
    baseURL: engineBinaryBaseURL
  )
}
